### ISSUE TITLE
The Pacemaker is not able to select master 

### ISSUE THREAD

**Issue by Puneet-Mathur** [dalibo/PAF#100]
I have configured a Postgresql cluster for hot_standy on the slave but as soon as I completed the configuration the cluster is not able to select the master and both the DBs are in standby mode, have become read-only:

Failed actions:
    pgsqld_promote_0 (node=puneet-ubuntu-cluster2, call=513, rc=1, status=complete, last-rc-change=Wed Jun 21 03:02:20 2017
, queued=300ms, exec=0ms
): unknown error
    pgsqld_promote_0 (node=puneet-ubuntu-cluster1, call=243, rc=1, status=complete, last-rc-change=Wed Jun 21 03:03:39 2017
, queued=114ms, exec=0ms
): unknown error

**Comment by ioguix** [comment]
Hello,

It miss a lot of information here to be able to answer...

First, how did you start your cluster ? Does your PostgreSQL instances were shut down ? What is your Pacemaker setup ? How did you setup your recovery.conf.pcmk ?

**Comment by Puneet-Mathur** [comment]
Hello Jehan,

First of all, Thanks a lot for your response.

I had a cluster running and then added the postgresql resource and the IP resource to it. Yes the postgres instances were shut when I added the postgres resource to lcuster on both the nodes.

The pacemaker is a very simple setup with 2 nodes. I can provide the crm configure show if you need. The recovery.conf.pcmk is set as a template in cluster and resides in/etc/postgres/9.6/main/.

Please let me know if you need any kind of details further.

Thanks and Regards
Puneet Mathur

**Comment by ioguix** [comment]
Hi,

Yes, could you provide your recovery.conf.pcmk file content and your pacemaker setup ?

**Comment by Puneet-Mathur** [comment]
Hello Jehan,

Please find the required below:

puneet@puneet-ubuntu-cluster1:/etc/postgresql/9.6/main$ cat recovery.conf.pcmk
standby_mode = on
primary_conninfo = 'host=10.0.1.121 application_name=puneet-ubuntu-cluster1'
recovery_target_timeline = 'latest'

puneet@puneet-ubuntu-cluster1:/etc/postgresql/9.6/main$ sudo crm status
[sudo] password for puneet:
Last updated: Wed Jun 21 11:20:46 2017
Last change: Wed Jun 21 02:38:47 2017 via cibadmin on puneet-ubuntu-cluster2
Stack: corosync
Current DC: puneet-ubuntu-cluster2 (2) - partition with quorum
Version: 1.1.10-42f2063
2 Nodes configured
3 Resources configured


Online: [ puneet-ubuntu-cluster1 puneet-ubuntu-cluster2 ]

Master/Slave Set: pgsql-ha [pgsqld]
     pgsqld     (ocf::heartbeat:pgsqlms):       Slave puneet-ubuntu-cluster1 (unmanaged) FAILED
     Slaves: [ puneet-ubuntu-cluster2 ]

Failed actions:
    pgsqld_promote_0 (node=puneet-ubuntu-cluster2, call=1647, rc=1, status=complete, last-rc-change=Wed Jun 21 11:09:32 2017
, queued=111ms, exec=0ms
): unknown error
    pgsqld_stop_0 (node=puneet-ubuntu-cluster1, call=261, rc=1, status=Timed Out, last-rc-change=Wed Jun 21 03:03:40 2017
, queued=60002ms, exec=0ms
): unknown error

puneet@puneet-ubuntu-cluster1:/etc/postgresql/9.6/main$ sudo crm configure show
node $id="1" puneet-ubuntu-cluster1 \
        attributes master-pgsqld="1"
node $id="2" puneet-ubuntu-cluster2 \
        attributes master-pgsqld="1"
primitive pgsql-master-ip ocf:heartbeat:IPaddr2 \
        params ip="10.0.1.121" cidr_netmask="24" \
        op monitor interval="10s"
primitive pgsqld ocf:heartbeat:pgsqlms \
        params pgdata="/var/lib/postgresql/9.6/main" bindir="/usr/lib/postgresql/9.6/bin" pghost="/var/run/postgresql" recovery_template="/etc/postgresql/9.6/main/recovery.conf.pcmk" start_opts="-c config_file=/etc/postgresql/9.6/main/postgresql.conf" \
        op start timeout="60s" interval="0" \
        op stop timeout="60s" interval="0" \
        op promote timeout="30s" interval="0" \
        op demote timeout="120s" interval="0" \
        op monitor interval="15s" timeout="10s" role="Master" \
        op monitor interval="16s" timeout="10s" role="Slave" \
        op notify timeout="60s" interval="0"
ms pgsql-ha pgsqld \
        meta master-max="1" master-node-max="1" clone-max="2" clone-node-max="1" notify="true"
colocation ip-with-master inf: pgsql-master-ip pgsql-ha:Master
order demote-then-stop-ip Mandatory: _rsc_set_ pgsql-ha:demote pgsql-master-ip:stop symmetrical=false
order promote-then-ip Mandatory: _rsc_set_ pgsql-ha:promote pgsql-master-ip:start symmetrical=false
property $id="cib-bootstrap-options" \
        dc-version="1.1.10-42f2063" \
        cluster-infrastructure="corosync" \
        stonith-enabled="false" \
        no-quorum-policy="ignore"


Thanks and Regards
Puneet Mathur

**Comment by ioguix** [comment]
Hi,

What versions of Ubuntu, Corosync and PAF are you using?

**Comment by Puneet-Mathur** [comment]
Hello Jehan,

Please find the versions from both nodes of cluster respectively below:

puneet@puneet-ubuntu-cluster1:~$ sudo uname -v
#50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016

puneet@puneet-ubuntu-cluster1:~$ sudo corosync -version
Corosync Cluster Engine, version '2.3.3'
Copyright (c) 2006-2009 Red Hat, Inc.

puneet@puneet-ubuntu-cluster1:~$ sudo pacemakerd -$
Pacemaker 1.1.10
Written by Andrew Beekhof

puneet@puneet-ubuntu-cluster2:~$ sudo uname -v
#50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016

puneet@puneet-ubuntu-cluster2:~$ sudo corosync -version
Corosync Cluster Engine, version '2.3.3'
Copyright (c) 2006-2009 Red Hat, Inc.

puneet@puneet-ubuntu-cluster2:~$ sudo pacemakerd -$
Pacemaker 1.1.10
Written by Andrew Beekhof


Thanks a lot for you interest in this.

Thanks and Regards
Puneet Mathur

**Comment by ioguix** [comment]
...and the version of PAF you installed please ?

**Comment by Puneet-Mathur** [comment]
You mean the resource agents right ?

**Comment by ioguix** [comment]
Not the "resource-agents" package, I mean the version of PAF ("resource-agents-paf") you installed...how did you install it ? packages ? sources ? what version ?

**Comment by Puneet-Mathur** [comment]
I used “resource-agents-paf_2.1.0-1_all.deb””.

**Comment by ioguix** [comment]
OK,

As the release note emphasis, 2.x is not compatible with your version of Pacemaker:

```
WARNING: This version is only compatible with at least Pacemaker 1.1.13 using a corosync 2.x stack.
```

See https://github.com/dalibo/PAF/releases/tag/v2.1.0 .

Either upgrade your OS and version of Pacemaker/Corosync, or use v1.1 of PAF: https://github.com/dalibo/PAF/releases/tag/v1.1.0

**Comment by ioguix** [comment]
PS: the packaging has been fixed so PAF packages will refuse to install on a server with deprecated versions of Pacemaker/Corosync.

Sorry for the inconvenience.

**Comment by Puneet-Mathur** [comment]
Hello Jehan,

Thanks a lot for the help the cluster is working now but have one issue that the postgres is not replicating the data to the other node and only one node is having the ownership of the pgsqld resource and can’t be transferred            to other node. This is probably happening due to some score rules. I am not getting a way to resolve it. Could you help me with that too?

Thanks and Regards
Puneet Mathur

**Comment by ioguix** [comment]
Hi,

Open a new issue, add your procedure, conf, history and information useful to help you.

Regards,
