### ISSUE TITLE
Result of monitor operation for pgsqld on nodename: Timed Out

### ISSUE THREAD

**Issue by Markus-** [dalibo/PAF#107]
Hi,

out of nothing last night our replication failed.

corosync.log

> Jul 11 22:31:17 nodename lrmd[3396]: warning: pgsqld_monitor_16000 process (PID 45046) timed out
> Jul 11 22:31:17 nodename lrmd[3396]: warning: pgsqld_monitor_16000:45046 - timed out after 10000ms
> Jul 11 22:31:17 nodename crmd[3400]:   error: Result of monitor operation for pgsqld on clusternode-name: Timed Out
> Jul 11 22:31:50 nodename pgsqlms(pgsqld)[45061]: INFO: pgsql_notify: trying to start failing slave "pgsqld"...
> Jul 11 22:31:51 nodename pgsqlms(pgsqld)[45061]: INFO: pgsql_notify: state is "in archive recovery" after recovery attempt
> Jul 11 22:31:51 nodename lrmd[3396]:  notice: pgsqld_notify_0:45061:stderr [ pg_ctl: another server might be running; trying to start server anyway ]
> Jul 11 22:31:51 nodename lrmd[3396]:  notice: pgsqld_notify_0:45061:stderr [ pg_ctl: could not start server ]
> Jul 11 22:31:51 nodename lrmd[3396]:  notice: pgsqld_notify_0:45061:stderr [ Examine the log output. ]
> Jul 11 22:31:51 nodename crmd[3400]:  notice: Result of notify operation for pgsqld on clusternode-name: 0 (ok)
> Jul 11 22:32:01 nodename pgsqlms(pgsqld)[45105]: INFO: pgsql_stop: instance "pgsqld" stopped
> Jul 11 22:32:01 nodename crmd[3400]:  notice: Result of stop operation for pgsqld on clusternode-name: 0 (ok)

In all other logfiles I don't find any hints for the reason - any suggestions where to look?
What does pgsqld_monitor_16000 process mean?

Regards
Markus

**Comment by blogh** [comment]
Hi, 

"pgsqld_monitor_16000" refers to the monitor action of the "pgsqld" agent which is setup with a "16s"  interval and "10s" timeout (in this case). the on-fail action depends on the configuration, version and action itself.

Can you give more info on you setup ? (versions, pacemaker conf) 
Did you : 
- have a network problem (did the standby lag at the sametime ?)
- reach max_connections (including superuser_reserved_connections) ?

Benoit

**Comment by Markus-** [comment]
RHEL 7.3 with HA-Add on, combined with stable RPM (PAF 2.1.0).

Systems are setup with the instructions of this site.

The thing is I just find two hints in the logfiles:
1. corosync.log: The named timeout-line @ the slave
2. postgres.log: ... shut down by administrator (-> pacemaker shutted it down)

So no hint in messages or any other logfile. 

What does the pgsqld_monitor "checks" in detail?

Regards
Markus

**Comment by blogh** [comment]
Hi !

As for most actions, the configuration is validated first (action: validate_all):
- presence of binaries
- presence of directories and critical files
- check of the recovery template (standby_mode, recovery_target_timeline and primary_conninfo)
- check if the user exist
- check the version of PostgreSQL

Then monitor starts:
```
Perform pg_is_ready (not timeout setting here)
If rc = 0 
	Perform pg_is_in_recovery() to identify the role of the local node. 
	If it fails we issue a OCF error code.
else if rc = 1 => rejecting connection
	we check the status in the control_file. 
	If the result is consistent with rc1, we try to check for pg_is_in_recovery() anyway.
	other wise we issue a OCF error code.
else if rc = 2 => server doesn't answer the connection attempt
	we check if it was correctly stopped and issue a OCF error code if not.
else (rc:3 or anything else)
	we return a OCF error.
end if
```
Benoit

**Comment by Markus-** [comment]
You mentioned a potential network problem above:
Arent't these checks local?
If not: What does the master do to monitor the slave?

Markus

**Comment by blogh** [comment]
You are right the network thing is not relevant.

The monitor is a local check.
But after the pg_is_in_recovery if we are on the master we update the scores with the info from pg_stat_replication.

**Comment by Markus-** [comment]
Ok, so are there any thresholds if the slave is too much behind anything happens?
If not I would say "magic issue" and give up. Because without any logfiles I can't really debug...

Markus

**Comment by ioguix** [comment]
Hello @Markus-,

The check was 100% local and on a standby as you stated (and as the action looks like).

For some reason, it timed out after 10s. That means the monitor didn't failed with an error code, it just did not finish soon enough, which is kind of weird considering how fast this action is supposed to be. Did you node was under a massive load? Do you have something else between Pacemaker and the PostgreSQL resource like a pooler? Do you connect through the socket file or the tcp/ip stack on localhost?

Did the corosync.log file shows anything else on the node itself?

What is your `migration-threshold` value for this resource? By default, after a failure, Pacemaker tries to "recover" the resource. For a slave, if the `migration-threshold` allows more failures, it will `stop->start` the resource in a transition (demote->stop->start->promote for a master). In your case, it seems it only stopped it.

> Ok, so are there any thresholds if the slave is too much behind anything happens?

Not by default, not with 2.1 (there's a new parameter in 2.2). But anyway, your problem does not comes from some standby lagging. The monitor action just did not finish fast enough. 

Is it the `lrm`, the pgsqlms or the PostgreSQL process that was stuck in a bad shape? Hard to say without more informations :/

Do you have anything that seems related on the system side?

**Comment by Markus-** [comment]
As statet before - No further information available. The OS- / Storage- / Network-Guys can't help so I'll give up. I will check the monitoring if there are any further hints regarding the Load-Situation.

There was "nothing" wrong - Because of missing restore_command in recovery.conf the archive of the master was not available, so the slave can't catch up with the master. After implementing the restore_command everything works as expected... (but no reason for the initial problem)

Thanks for the hints - I will close the issue.
Markus
