### ISSUE TITLE
Avoid alert when adding node just for quorum

### ISSUE THREAD

**Issue by alexaht** [dalibo/PAF#109]
Hi,

Have configured cluster with two fully worked nodes. Trying to add into cluster one more node just for a quorum to avoid split brain. But always get 
"pgsqld_stop_0 on node3 'invalid parameter' (2): call=88, status=complete, exitreason='none',
    last-rc-change='Wed Jul 19 14:10:38 2017', queued=0ms, exec=79ms"
is it possible to somehow disable monitor action on this node, I already banned all resources from this node. Also, was trying to make node standby, but pacemaker still trying to run the monitor on that node.
With configuration pgsql-ha master/slave clone-max = 2.
Any advise?

**Comment by ioguix** [comment]
> Any advice ?

Documentation :D

See: http://dalibo.github.io/PAF/CentOS-7-admin-cookbook.html#forbidding-a-paf-resource-on-a-node

**Comment by alexaht** [comment]
Many thanks, it's my bad doesn't know how I missed it. Has read documentation many times.
One more time many many thanks, your 'pgsqlms' script is awesome.

**Comment by ioguix** [comment]
Thank you :)
