### ISSUE TITLE
Saturation of a File System of a Primary Instance

### ISSUE THREAD

**Issue by did16** [dalibo/PAF#111]
Hi
I have tested Cluster Linux Pacemaker/Corosync/PAF and when a File system (pg_xlog for instance) is saturated , the primary instance stops and Pacemaker/Corosync/PAF does not make a failover.
Is it normal ? Will the next version of PAF will fix the problem ?

**Comment by ioguix** [comment]
Hi,

There's no reason PAF/Pacemaker would not detect such a failure and failover to the another node. If `pg_xlog` space is saturated, PostgreSQL is supposed to stop with a `PANIC` message. Such failure would be detected by PAF and Pacemaker would try to recover it and eventually failover to another node. The number of recovers before failing over another node depend on your Pacemaker setup.

We need to check your cluster is properly setup before discussing a problem in PAF.

Please answer questions #113.
