### ISSUE TITLE
Loss of the FO network interface

### ISSUE THREAD

**Issue by did16** [dalibo/PAF#112]
Hi
I have tested Linux cluster with pacemaker/corosync/PAF and after the loss of the Front Office network interface, there is not a failover. 
will the next version of PAF fix this problem ?

Thanks in advance

**Comment by ioguix** [comment]
Hi,

I'm not sure to understand exactly what you mean.

If you are talking about the network between the clients and PostgreSQL, this is not related to the PAF resource agent as the PostgreSQL instance itself is perfectly fine. You should consider other solutions to covers your network issues (redundant networks, move resources based on network quality, etc).
