### ISSUE TITLE
Lost of the storage on the primary server

### ISSUE THREAD

**Issue by did16** [dalibo/PAF#113]
HI
We have tested Linux cluster/pacemaker/corosync/PAF and when there is the loss of the storage on the primary server  there is no failover. 
will the next version of PAF fix the problem ?

Thanks in advance

**Comment by ioguix** [comment]
Hi,

You did not give us any kind of information about your cluster, setup, fencing method, number of node, etc. Nothing.

In my experience, if you pull the disks or storage out of the server, PAF/Pacemaker actually failover everything. 

Did you check in the first place your setup and basic failover?

Same question for your other issues.
