### ISSUE TITLE
Node does not migrate when resource blocked

### ISSUE THREAD

**Issue by alexaht** [dalibo/PAF#118]
Hi,

I have an unusual situation when one of the administrators performed "yum update" PostgreSQL was updated and the system has tried to restart Postgres. After this action system has set blocked state to Postgres resource, it was in read-only mode and do not migrate to another node.

I have found another way to reproduce such behavior:
on working cluster just rename Postgres DB 'data' dir and system also manage it as blocked and do not perform any migrate operations at all.

Is there a way to allow the system to migrate on working redundancy node?  I have tried to add to monitor operation on-fail=standby but nothing work...:(

**Comment by Markus-** [comment]
Nothing to help, but are you sure that the yum update run tried to restart the server?
Which repository are you using? The official RHEL or the PostgreSQL.org? My experiences with the second one are different - here you have to restart PostgreSQL manually

**Comment by alexaht** [comment]
Hi Markus,

I'm using PostgreSQL.org repo, and yes I have investigated and seen that updated has called for PostgreSQL restart.
Aug 15 12:15:39 test-1 yum[15192]: Updated: postgresql94-server-9.4.13-1PGDG.rhel7.x86_64
Aug 15 12:15:39 test-1 yum[15192]: Updated: dsucatalog-17.07.00-WWD05.noarch
Aug 15 12:15:39 test-1 systemd: Reloading.
Aug 15 12:15:39 test-1 systemd: Stopping PostgreSQL 9.4 database server...

As you can see by this log records. After this PostgreSQL is being changed to read-only mode and does not migrate to another node.

**Comment by blogh** [comment]
Hi,

Do you have enabled fencing ? Block is the default state when pacemaker fails to stop a ressource and has no fencing enable. I am thinking that maybe pacemaker has seen that the ressource was in a wrong state and tried to restart it while postgres was being upgraded / restarted. Since it failed, pacemaker blocked the ressource.

Can you share more info about the cluster config ?
Do you have something interesting in you postgres log ?

Benoit.

**Comment by alexaht** [comment]
Hi,

Current configuration with disabled fencing. I'm pretty sure you are right, cause I'm coming for the same results in my investigation. 

Regarding cluster configuration, I'm using recommended by PAF configuration. Regarding logs, they clearly show that it has received sig term caused by yum update. 

I would like to create a testing environment with enabled software fencing watchdog and try different ways of failover.

**Comment by ioguix** [comment]
Hi,

I can see two issues here:
* you __must__ always pay attention to your cluster stack on every admin task, especially during yum update, even more if one of the service is upgraded. Before updating your system, put your cluster in maintenance mode or shut it down.
* you __must__ use fencing with PAF :)

Regards,

**Comment by ioguix** [comment]
Do you have any other questions related to this subject or could we close this issue?

**Comment by alexaht** [comment]
No, thanks.

I will try to make a configuration with sbd enabled and a soft version of the watchdog and look how it would work.

**Comment by ioguix** [comment]
Hi,

In regard with watchdog, look at the admin cookbooks and fencing pages in the PAF documentation.

Note that watchdog is a small step toward fencing, but not the full path to it...Make sure to have some real fencing setup at some point.
