### ISSUE TITLE
You must set meta parameter notify=true for your master resource

### ISSUE THREAD

**Issue by Fiddich** [dalibo/PAF#121]
The latest Quickstart for Centos 7 does not work on RHEL 7.4
This has to be related to https://bugzilla.redhat.com/show_bug.cgi?id=1458153

Failed Actions:
* pgsqld_monitor_0 on iictyibdlv003 'not installed' (5): call=86, status=complete, exitreason='You must set meta parameter notify=true for your master resource',
    last-rc-change='Thu Oct  5 09:59:36 2017', queued=0ms, exec=70ms
* pgsqld_monitor_0 on iictyibdlv001 'not installed' (5): call=70, status=complete, exitreason='You must set meta parameter notify=true for your master resource',
    last-rc-change='Thu Oct  5 09:59:36 2017', queued=0ms, exec=71ms
* pgsqld_monitor_0 on iictyibdlv002 'not installed' (5): call=68, status=complete, exitreason='You must set meta parameter notify=true for your master resource',
    last-rc-change='Thu Oct  5 09:59:36 2017', queued=0ms, exec=71ms

**Comment by Fiddich** [comment]
Seems to be fixed

**Comment by ioguix** [comment]
I'm not sure to understand what's the point of this issue. 

It seems you just forgot to add notify=true, isn't it? This is written in the quick start there: http://dalibo.github.io/PAF/Quick_Start-CentOS-7.html#cluster-resources

Could you add some more details?

**Comment by Fiddich** [comment]
Hi,
We can close the incident. 
Because of another bug (Error: Could not map name=.... to a UUID) when using pcs -f, I could not place the cluster cib changes in an xml first. 
So the pgsqld resource only worked after a pcs resource cleanup, as I had to do the changes interactively.

Can be closed

**Comment by ioguix** [comment]
I'm not aware of this bug with `pcs -f`. As I enjoy using it, do you have any doc/pointers related to this?

Thank you!

**Comment by Fiddich** [comment]
pcs -f cluster1.xml resource defaults migration-threshold=5
Error: Could not map name=xxxx to a UUID

I suppose its this one (not sure, too busy ;) )
https://bugzilla.redhat.com/show_bug.cgi?id=1374175

Is it possible this is caused by resource-agents-paf ? 
I don't have this issue on clusters without.....

**Comment by ioguix** [comment]
I hardly think it could be related to PAF in some way. It sounds like the CRM is not able to link a nodename to its id from the underlaying cluster layer (eg. corosync).

Anyway, thank you.
