### ISSUE TITLE
Quickstart CentOS7 improvements

### ISSUE THREAD

**Issue by daftaupe** [dalibo/PAF#122]
Hello,

I'm following the quickstart guide and there are 2 things that are not working straightforward.

- it seems that the 2 following lines need resources to be run without error.
> pcs -f cluster1.xml resource defaults migration-threshold=5
> pcs -f cluster1.xml resource defaults resource-stickiness=10 

Even if it's written 
>This sets two default values for resources we create in the next chapter:

They should be after the block defining the first ressources. Or the text should mention to wait for the first resources so they could be run.

- when creating the resources in the node fencing section I guess you should add a line like 'ssh-keygen' at least so ssh-copy-id <user>@192.168.122.1 and the /root/.ssh/id_rsa in the command line refer to something existing.

Regards,

**Comment by ioguix** [comment]
> it seems that the 2 following lines need resources to be run without error

They run fine without any error, even without resource defined. These default values are global to the cluster. In fact, the problem is something else... It just shouldn't mention `-f cluster1.xml`.

> when creating the resources in the node fencing section I guess you should add a line like 'ssh-keygen' 

Done.

Thank you for your report!

**Comment by daftaupe** [comment]
Thanks for the quick fix, one last thing (I'm at the end of the quickstart and the cluster is working :) ) : in the following commands, it's not super clear that srv[1-3]-c7 is the name of the virtual machine in libvirt. Adding just a simple line to explain it would be very helpful I guess.

> pcs -f cluster1.xml stonith create fence_vm_srv1 fence_virsh \
>   pcmk_host_check="static-list" pcmk_host_list="srv1"        \
>   ipaddr="192.168.122.1" login="<user>" port="srv1-c7"       \
>   action="off" identity_file="/root/.ssh/id_rsa"
> 
> pcs -f cluster1.xml stonith create fence_vm_srv2 fence_virsh \
>   pcmk_host_check="static-list" pcmk_host_list="srv2"        \
>   ipaddr="192.168.122.1" login="<user>" port="srv2-c7"       \
>   action="off" identity_file="/root/.ssh/id_rsa"
> 
> pcs -f cluster1.xml stonith create fence_vm_srv3 fence_virsh \
>   pcmk_host_check="static-list" pcmk_host_list="srv3"        \
>   ipaddr="192.168.122.1" login="<user>" port="srv3-c7"       \
>   action="off" identity_file="/root/.ssh/id_rsa"

**Comment by ioguix** [comment]
> I'm at the end of the quickstart and the cluster is working :)

Congrats!

> it's not super clear that srv[1-3]-c7 is the name of the virtual machine in libvirt. Adding just a simple line to explain it would be very helpful I guess.

Done. Thank you for your suggestions!
