### ISSUE TITLE
Create Debian Package

### ISSUE THREAD

**Issue by ioguix** [dalibo/PAF#13]
This issue is just a reminder to create the debian package when releasing 1.1.0.

**Comment by ARogovsky** [comment]
Hi!
I show you have debian directory and easy build deb package via  dpkg-buildpackage -us -uc
...
```
Building PAF
Installing /root/PAF/debian/resource-agents-paf/usr/share/man/man1/pgsqlms.1p
Installing /root/PAF/debian/resource-agents-paf/usr/lib/ocf/lib/heartbeat/OCF_Directories.pm
Installing /root/PAF/debian/resource-agents-paf/usr/lib/ocf/lib/heartbeat/OCF_ReturnCodes.pm
Installing /root/PAF/debian/resource-agents-paf/usr/lib/ocf/lib/heartbeat/OCF_Functions.pm
Installing /root/PAF/debian/resource-agents-paf/usr/share/man/man3/OCF_Directories.3pm
Installing /root/PAF/debian/resource-agents-paf/usr/share/man/man3/OCF_Functions.3pm
Installing /root/PAF/debian/resource-agents-paf/usr/share/man/man3/OCF_ReturnCodes.3pm
Installing /root/PAF/debian/resource-agents-paf/usr/lib/ocf/resource.d/heartbeat/pgsqlms
Installing /root/PAF/debian/resource-agents-paf/usr/share/resource-agents/ocft/configs/pgsqlms
```
...

**Comment by ioguix** [comment]
Hello ARogovsky,

Yes, I created and setup the debian folder two weeks ago, while working on your first issue.

I plan to build the package with the official release of 1.1. I create this issue to keep track of it.

**Comment by ioguix** [comment]
I created the first debian package for 1.0.1. It seems to install or upgrade (with a previous 1.0.0 one) with no issue.

No need to keep this issue open.

**Comment by ge-fa** [comment]
Should this go into Debian stretch, currently testing, which is to be expected ~ Q1/Q2 2017?

**Comment by ioguix** [comment]
Hi @ge-fa,

No, branch 1.x of PAF is for older versions of Pacemaker/Corosync stacks. This issue was created to make sure we don't forget to build packages for 1.0 as our dev effort is focused on 2.1.

Basically:
* 1.x is compatible with Debian 7
* 2.x is compatible with Debian 8 and after

I believe PAF 2.0 is a better candidate for stretch and it is already released. However, I hope 2.1 will be released fairly soon. Maybe it worth waiting a bit to avoid packaging effort for both 2.0 then 2.1? I'll publish the Debian packages anyway.

**Comment by ge-fa** [comment]
> No, branch 1.x of PAF is for older versions of Pacemaker/Corosync stacks. This issue was created to make sure we don't forget to build packages for 1.0 as our dev effort is focused on 2.1.

Sorry, I've overlooked this.

> I believe PAF 2.0 is a better candidate for stretch and it is already released. However, I hope 2.1 will be released fairly soon. Maybe it worth waiting a bit to avoid packaging effort for both 2.0 then 2.1? I'll publish the Debian packages anyway.

The [deadlines](https://wiki.debian.org/DebianStretch#Debian_Stretch_Life_cycle) are quite fast approaching. Is there any ETA for 2.1?

**Comment by ioguix** [comment]
> The [deadlines](https://wiki.debian.org/DebianStretch#Debian_Stretch_Life_cycle) are quite fast approaching. Is there any ETA for 2.1?

If I understand correctly these deadline, new packages are accepted until January 5th of 2017, right ?

We'll try to publish the 2.1 release in December. If it's not ready, then 2.0 is appropriated for stretch.

**Comment by ge-fa** [comment]
> If I understand correctly these deadline, new packages are accepted until January 5th of 2017, right ?

Exactly.

> We'll try to publish the 2.1 release in December. If it's not ready, then 2.0 is appropriated for stretch.

Could you please ping me, when 2.1 gets released?

**Comment by ioguix** [comment]
> Could you please ping me, when 2.1 gets released?

I just added an issue to track this. Thank you @ge-fa!
