### ISSUE TITLE
manual failover when all servers go down and only a standby comes back.

### ISSUE THREAD

**Issue by blogh** [dalibo/PAF#26]
Hi,

I am testing a senario with 2 servers where both the standby and the master go down (in that order).
Then only the slave goes back online.

The standby is never promoted as a primary (I can understand why).

The only way I found to do it was to issue the "pg_ctl promote -D $PGDATA" myself. (<=> manual failover).
Is there a way to do it with the crm commands ? (just moving the resource didn't do it).

Benoit.

Conf: Ubuntu 14.04 // PG 9.4 // Corosync 2.3.3 // Pacemaker 1.1.10 // PAF 1.1

**Comment by ioguix** [comment]
It really depends on your setup and what you did to get your nodes down.

After your test:
1) what are the scores in your cluster using `crm_simulate -sL`?
2) what are the failcounts of the resource on each nodes using `crm_failcount`?

If you are not able to move your resource to the second node, I suppose that this means you have a `-INFINITY` score on the node hosting the standby for this resource. Moving a resource is only a matter of setting the score to `INFINITY` on the target node, but `-INFINITY + INFINITY = -INFINITY`.

**Comment by blogh** [comment]
Hi,

I think it can't be quorum since I have two nodes and no-quorum-policy="ignore".

I cannot do the crm_simulate you asked for before bringing up the first node since there is no pacemaker. (did I miss something ?)
I took the /var/log/syslog traces with PAF in debug mode and attached it just in case one of the tests seems interesting to you.

Sorry for the noise if it's the expected behavior. If you need more info, I redo another run. 

I tried 3 different things to stop the nodes. 

**CASE 1:** normal stop. dont understand
1. service pacemaker stop on **slave**
2. service corosync stop on **slave**
3. service pacemaker stop on master
4. service corosync stop on master 
5. service corosync start on **slave**
6. service pacemaker start on **slave**
7. service corosync start on master
8. service pacemaker start on master

The old master is fenced but the standby is stucked in standby mode (master-pgsqlsrv = 1000 & failcount og msPostgresql is 0). When I bring up the master, I do "crm resource cleanup msPostgresql" and everything goes back to the original state.

I dont understand this... is it expected ?

(files pacemakerstop*)

**CASE 2:** standby stop. works as expected from me

1. put the pacemaker resource in stanbdy **on slave**
2. service pacemaker stop on **slave**
3. service corosync stop on **slave**
4. put the pacemaker resource in stanbdy
5. service pacemaker stop on master
6. service corosync stop on master 
7. service corosync start on **slave**
8. service pacemaker start on **slave**
9. put the pacemaker resource back to online on **slave**
10. service corosync start on master
11. service pacemaker start on master
12. put the pacemaker resource back to online

In this case the old master is fenced. And msPostgresql:master goes on the former standby. I can understand that since the old master is in standby mode <=> not available to allocate ressource.

(files pacemakerstop_standby*)

CASE 3: kernel pannic stop. works as expected from me
1. kernel panic on the **slave** (echo c | sudo tee /proc/sysrq-trigger)
2. kernel panic on the master (echo c | sudo tee /proc/sysrq-trigger)
3. service corosync start on **slave**
4. service pacemaker start on **slave**
5. service corosync start on master
6. service pacemaker start on master


In this case the old master is fenced. And msPostgresql:master goes on the former standby. I can understand that, the master is dead after all.

(files kernelpanic*)
	
Benoit.

[kernelpanic_x64lmwbio9g.txt](https://github.com/dalibo/PAF/files/321009/kernelpanic_x64lmwbio9g.txt)
[pacemakerstop_standby_status.txt](https://github.com/dalibo/PAF/files/321005/pacemakerstop_standby_status.txt)
[pacemakerstop_standby_x64lmwbio9f.txt](https://github.com/dalibo/PAF/files/321008/pacemakerstop_standby_x64lmwbio9f.txt)
[pacemakerstop_standby_x64lmwbio9g.txt](https://github.com/dalibo/PAF/files/321007/pacemakerstop_standby_x64lmwbio9g.txt)
[pacemakerstop_status.txt](https://github.com/dalibo/PAF/files/321010/pacemakerstop_status.txt)
[pacemakerstop_x64lmwbio9f.txt](https://github.com/dalibo/PAF/files/321002/pacemakerstop_x64lmwbio9f.txt)
[pacemakerstop_x64lmwbio9g.txt](https://github.com/dalibo/PAF/files/321003/pacemakerstop_x64lmwbio9g.txt)
[kernelpanic_status.txt](https://github.com/dalibo/PAF/files/321006/kernelpanic_status.txt)
[kernelpanic_x64lmwbio9f.txt](https://github.com/dalibo/PAF/files/321004/kernelpanic_x64lmwbio9f.txt)

**Comment by ioguix** [comment]
Hi @blogh !

Sorry, I have not a lot of time to study closely your case 1, but here are some quick thoughts about it:

  * your processes seems quite fast for some manual operation. Are you automating this test ?
  * How much time do you wait after shutting down the master and after the slave startup ? I can not find any information in your logs about the cluster not being able to find a resource to promote. Some transition are aborted because of new events though
  * After the shutdown of the slave, a master set a score of -1000 on it because it is not in replication anymore. That forbid a promote on it if the score doesn't move to a positif number anymore.

to verify the last assumption, could you:
  * stop the slave
  * wait for its score to be set to -1000 
  * stop the master
  * start the slave
  * wait one minute
  * set its master score to 1000 if it has not been promoted yet

Thanks

**Comment by blogh** [comment]
Thanks for the pointers. I will try that. If you think it cannot be a PAF problem I'll close the issue.

**Comment by ioguix** [comment]
No, I'm not sure right now.

I feel like it could be the negative score set by the master when the slave went away. I didn't thought much about this, but there's no reason for this score to move up. If this is the issue, then I have no solution right now to deal with this issue. This behavior would not be a bug in PAF but its normal behavior in the current implementation.

Wde'll have to think about this exact scenario ( loosing the slaves, then the master ) and how the cluster show react to this. It might lead to a future refactoring in PAF.

**Comment by blogh** [comment]
Hi,

Everythink worked out as you said, the slave's score was set to -1000 and was never raised after restart.
I think I understand this case better now.

All in all, I am not sure it's a problem. 
* In case of a crash of slave then master, if only the salves comes back I think it's normal that we failover. (CASE 2)
* The "standby" case is expected also in my opinion. (CASE 3) (I did the same while setting the nodes in maintenance mode with the same outcome)
* I also tried just killing the pacemaker processes on slave then primary and start slave first. It fails over. (Pacemaker is down but the instance is still up so the score on the standby is still 1000. Is it normal to monitor the standby when the node is down ?)(I have trouble mapping this case to a real word issue)
* For the CASE 1, I think it's a weird case. It looks more like a misuse of the cluster. Maybe just documenting it would be enought ?

I would be interested to know what tests you do ? Here is my list.

* Switchover
* Complete stop/restart of the cluster
* Standby crashed, corosync is still up
* Standby crashed, corosync is still up. But the standby doesn't restart.
* Primary crashed, corosync is still up
* Primary crashed, corosync is still up. But the Primary doesn't restart.
* Primary kernel panic
* Standby kernel panic
* Standby then master crash. Standby goes online first
* Standby then master (kill pacemaker process). Standby goes online first
* Standby then master stop (serice pacemaker stop). Standby goes online first
* Standby then master stop (serice pacemaker stop + nodes in standby mode). Standby goes online first
* Standby then master stop (serice pacemaker stop + nodes in maintenance mode). Standby goes online first
* After switchover postgres config error in postgresql.conf
* After switchover postgres config error in recovery.conf (application name cf ISSUE 25)

I plan on adding : VM stop and network disconnected as soon I have proper vmware fencing. 
Am I missing something obvious ?

Benoit

**Comment by ioguix** [comment]
Hi @blogh,

Sorry for the delay to answer your last message. I'll get back to you as soon as I can take some minute to read everything carefully.

To answer your last question, bellow are the tests I am doing before pushing code to github. They are all done on a three node cluster with fencing and quorum. I actually never do tests on a two node cluster or a cluster without fencing.

Here are the tests:
  * switchover
  * `pg_ctl -m fast stop` on the slave
  * `pg_ctl -m fast stop` on the master
  * `pg_ctl -m immediate stop` on the slave
  * `pg_ctl -m immediate stop` on the master
  * `echo c > /proc/sysrq-trigger` on the master
  * `echo c > /proc/sysrq-trigger` on the master while the designated best slave is actually not the best slave to promote.

I really appreciate your feedback on your tests. Thank you.

Regards,

**Comment by blogh** [comment]
Hi,

I have been thinking about this for a while. Shouldn't we set the master score to -1000 after we stop PostgreSQL and the current score is 1000 (<=> not the master).

It would ensure that a former standby is never started as primary at cluster start without notice. After thinking about CASE 2 for a while I am uncomfortable with the situation.
- put the slave node in standby then stop
- put the master node in standby then stop
- start the salve node => promoted, we lost data

I understand that standby mode means the node cannot host resources. But should we risk blindly losing data in that case ?  

Benoit

**Comment by ioguix** [comment]
Hi,

After some thoughts, I'm not sure to understand this test case number 2.

When you stop the slave first, or when it crashes, its score is set to -1000 by the master during the next monitor action.

If you are fast enough run your test case 2, then the master might not be able to set the slave score to a negative one. That means that on the next start, its score is high enough to allow the slave promotion.

How do you deal with quorum in your setup? Did you enable it in corosync with the `two_node` parameter? It might help in this scenario: on a fresh cluster startup, because `two_node` imply `wait_for_all`, Pacemaker will wait for both nodes to be up before doing actions.

**Comment by blogh** [comment]
Hi ,

Yes, I use the two_node parameter. In pacemaker, I set no-quorum-policy=ignore. So I believe it shouldn't wait for both nodes to be up to do stuff.

If I understand correctly, this code should set the score of my standby to -1000: (_check_locations)
```
# If there are still nodes in "partition_nodes", it means there is no
# corresponding line in "pg_stat_replication".
foreach my $node (split /\s+/ => $partition_nodes) {
    # Exclude the current node.
    next if $node eq $nodename;

    ocf_log( 'warning', sprintf
        '_check_locations: "%s" is not connected to the primary, set score to -1000',
        $node );
    _set_master_score( -1000, $node );
}
```
This code is based on : crm_node --partition
In my two situations:
- kernel panic => pacemaker and corosync are gone. The node is not part of the partition. So the score is not set to -1000.
- scripted sequence "put node in standby; stop pacemaker; stop coroync". In this situation pacemaker and corosync are gone too (so it's not in the partition). So the score is not set to -1000.

I tried to put the node in standby then wait and it behaves as you say.

Now I understand why you where talking about "waiting" and why the log had only this :
```
Aug 31 15:13:16 x64lmwbio9g pgsqlms(pgsqlsrv)[29077]: INFO: _check_locations: ignoring unknown application_name/node "x64lmwbio9f-priv"
```

I am not sure if it's good. 

Benoit

**Comment by ioguix** [comment]
> Yes, I use the two_node parameter. In pacemaker, I set no-quorum-policy=ignore. So I believe it shouldn't wait for both nodes to be up to do stuff.

Well, you should not set no-quorum-policy to ignore if corosync setup enable the two_node parameter.

> This code is based on : crm_node --partition [...]

Erf, you are right, I forgot about this `crm_node --partition`. We will have to refactor this at some point.

But first, could you test without the `no-quorum-policy=ignore`?

Sorry, I don't have enough time right now to make tests on a two node cluster myself. I hope I'll have some time next week.

Cheers,

**Comment by blogh** [comment]
Hi,

The documentation seems to say otherwise:
http://clusterlabs.org/doc/en-US/Pacemaker/1.1/html/Clusters_from_Scratch/_perform_a_failover.html

I'll try anyway.

Benoit

**Comment by ioguix** [comment]
Hi,

In my understanding (and comprehension of this parameter), the documentation you are pointing says what I wrote:

> The pcs cluster setup command will automatically configure two_node: 1 in corosync.conf, so a 
> two-node cluster will "just work".

=> Using the corosync parameter `two_node` allows to use quorum in a two node cluster.

> If you are using a different cluster shell, you will have to configure corosync.conf appropriately 
> yourself. 

=> If you don't use pcs, set it manually yourself.

> If you are using older versions of corosync, you will have to ignore quorum at the pacemaker level, 
> using pcs property set no-quorum-policy=ignore (or the equivalent command if 
> you are using a different cluster shell). 

=> And if your corosync old version does not support this parameter then set `no-quorum-policy=ignore`.

In fact, this parameter is not equivalent to `no-quorum-policy=ignore`. It allows to acquire the quorum on cluster startup, as soon as the nodes are available. But then, if one of them crash or shutdown, the other one will keep the quorum. When the other node will start again, should a network partition occurs, it will never be able to acquire the quorum and will wait for the second node to be visible. This is neat improvement compared to `no-quorum-policy=ignore`.

**Comment by ioguix** [comment]
By the way, `no-quorum-policy=ignore` is deprecated in crmsh in favor of `two_node`. See some more explanation here: http://clusterlabs.org/pipermail/developers/2016-September/000327.html

**Comment by ioguix** [comment]
I think we can close this issue. There is some solutions given here for this scenario and some more discussion happening in #56.

Cheers,
