### ISSUE TITLE
CentOS Documentation Corosync Configuration

### ISSUE THREAD

**Issue by yusufgungor** [dalibo/PAF#37]
Hi, in documentations (http://dalibo.github.io/PAF/documentation.html) there is not any "/etc/corosync/corosync.conf" configuration for CentOS 6 and CentOS 7 but Debian 8 has it. Is it forgotten or on purpose? 

http://dalibo.github.io/PAF/Quick_Start-Debian-8.html
http://dalibo.github.io/PAF/Quick_Start-CentOS-6.html
http://dalibo.github.io/PAF/Quick_Start-CentOS-7.html

**Comment by ioguix** [comment]
Hi @yusufgungor.

It's on purpose. Under centos, `pcs cluster setup` creates the corosync.conf file itself.

Under debian, `crmsh` is not able to do it because of packaging issues (see comment in the doc you pointed out), so we must take care of it by ourself.

**Comment by yusufgungor** [comment]
Thanks a lot.
