### ISSUE TITLE
PAF Auto Failback Support

### ISSUE THREAD

**Issue by yusufgungor** [dalibo/PAF#38]
Hi, my setup has only two node. My purpose is making active/passive postgresql cluster. If master is unreachable then slave must serve until master come back. 

I have two server (Centos 6.6) to test this situation. I installed the PAF as you documented, and i only changed:

pcs -f cluster1.xml resource master pgsql-ha pgsqld \
    master-max=1 master-node-max=1                  \
    **clone-max=3** clone-node-max=1 notify=true

to 

pcs -f cluster1.xml resource master pgsql-ha pgsqld \
    master-max=1 master-node-max=1                  \
    **clone-max=2** clone-node-max=1 notify=true

For testing purpose, disconnect the lan connection of master and monitored the situation from "pcs status", shared ip assigned to the slave and slave became Master.

After enabling the lan connection of the old Master, old Master became Master again, but in postgresql logs of slave server says:

> < 2016-09-04 17:39:06.245 EEST >LOG:  entering standby mode
> < 2016-09-04 17:39:06.255 EEST >LOG:  consistent recovery state reached at 0/3015B28
> < 2016-09-04 17:39:06.255 EEST >LOG:  invalid record length at 0/3015B28
> < 2016-09-04 17:39:06.255 EEST >LOG:  database system is ready to accept read only connections
> < 2016-09-04 17:39:06.257 EEST >FATAL:  pg_hba.conf rejects replication connection for host "10.0.0.36", user "postgres", SSL off
> < 2016-09-04 17:39:06.258 EEST >FATAL:  could not connect to the primary server: FATAL:  pg_hba.conf rejects replication connection for host "10.0.0.36", user "postgres", SSL off
> 
> < 2016-09-04 17:39:21.274 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:26.281 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:31.279 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:36.287 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:41.290 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:46.297 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:51.300 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:56.306 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:01.312 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:06.316 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:11.321 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:16.324 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:21.330 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:26.336 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:31.342 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:36.347 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:41.353 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:46.357 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:51.363 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3

Is this normal? Is it impossble to sync the old master with the new master before making old master to Master again?

If it is impossible, can we prevent the old master become to Master again after it come back? What do you offer to use in this situation? If we prevent the old master become to Master again after come back, can we sync it with the new master using pg_rewind tool?

Also, i did not config the corosync.conf and you said that "pcs cluster setup" does it for me, but i do not have "/etc/corosync/corosync.conf" file. Is this normal? Where can i write the "two_node: 1" ? I searched and i have "two_node" setting in "/etc/cluster/cluster.conf" as:

> ...<!cman broadcast="no" expected_votes="1" transport="udp" two_node="1"/>

is it enogh?

Also, my servers are on the vmware and in my setup i have not access to hypervisor. I can not use "fence_virsh" etc. Because of this, i disabled the STONITH like:

pcs property set stonith-enabled=false

after pushing the cib xml.

But event this, i got this repetitive errors in "/var/log/messages":

> Sep  4 17:41:04 node_01 fence_pcmk[9679]: Call to fence node_02 (reset) failed with rc=237
> Sep  4 17:41:04 node_01 stonith-ng[5395]:   notice: Operation reboot of node_01 by <no-one> for stonith_admin.cman.8195@node_02.5aa18e64: No such device
> Sep  4 17:41:04 node_01 crmd[5399]:   notice: Peer node_01 was not terminated (reboot) by <anyone> for node_02: No such device (ref=5aa18e64-e2c3-4be8-a2b0-c367ea7ef977) by client stonith_admin.cman.8195
> Sep  4 17:41:07 node_01 fence_pcmk[9715]: Requesting Pacemaker fence node_02 (reset)
> Sep  4 17:41:07 node_01 stonith-ng[5395]:   notice: Client stonith_admin.cman.9716.089f30fb wants to fence (reboot) 'node_02' with device '(any)'
> Sep  4 17:41:07 node_01 stonith-ng[5395]:   notice: Initiating remote operation reboot for node_02: 7e817e63-0497-42e9-b09e-0e4a22ae8ef8 (0)
> Sep  4 17:41:07 node_01 stonith-ng[5395]:   notice: Couldn't find anyone to fence (reboot) node_02 with any device
> Sep  4 17:41:07 node_01 stonith-ng[5395]:    error: Operation reboot of node_02 by <no-one> for stonith_admin.cman.9716@node_01.7e817e63: No such device
> Sep  4 17:41:07 node_01 crmd[5399]:   notice: Peer node_02 was not terminated (reboot) by <anyone> for node_01: No such device (ref=7e817e63-0497-42e9-b09e-0e4a22ae8e89) by client stonith_admin.cman.9716

Also in my "/etc/cluster/cluster.conf" file like this:

> <!cluster config_version="9" name="cluster_pgsql">
>   <!fence_daemon/>
>   <!clusternodes>
>     <!clusternode name="node_01" nodeid="1">
>       <!fence>
>         <!method name="pcmk-method">
>           <!device name="pcmk-redirect" port="node_01"/>
>         </method>
>       </fence>
>     </clusternode>
>     <!clusternode name="node_02" nodeid="2">
>       <!fence>
>         <!method name="pcmk-method">
>           <!device name="pcmk-redirect" port="node_02"/>
>         </method>
>       </fence>
>     </clusternode>
>   </clusternodes>
>   <!cman broadcast="no" expected_votes="1" transport="udp" two_node="1"/>
>   <!fencedevices>
>     <!fencedevice agent="fence_pcmk" name="pcmk-redirect"/>
>   </fencedevices>
>   <!rm>
>     <!failoverdomains/>
>     <!resources/>
>   </rm>
> </cluster>
- I add "!" after the "<"  sign, else the text editor of github hides them.

Should i remove the lines which refers to fencing like "<fence>...</fence>" and "<fencedevices>...</fencedevices>" ?

Thanks for your helps.

**Comment by yusufgungor** [comment]
My full postgresql logs are:

**Node1:** (Master)

> < 2016-09-04 17:29:34.261 EEST >LOG:  database system was shut down at 2016-09-04 17:28:46 EEST
> < 2016-09-04 17:29:34.273 EEST >LOG:  MultiXact member wraparound protections are now enabled
> < 2016-09-04 17:29:34.275 EEST >LOG:  database system is ready to accept connections
> < 2016-09-04 17:29:34.275 EEST >LOG:  autovacuum launcher started
> < 2016-09-04 17:29:48.603 EEST >LOG:  received fast shutdown request
> < 2016-09-04 17:29:48.603 EEST >LOG:  aborting any active transactions
> < 2016-09-04 17:29:48.603 EEST >LOG:  autovacuum launcher shutting down
> < 2016-09-04 17:29:48.604 EEST >LOG:  shutting down
> < 2016-09-04 17:29:48.607 EEST >LOG:  database system is shut down
> < 2016-09-04 17:29:57.298 EEST >LOG:  database system was shut down at 2016-09-04 17:29:48 EEST
> < 2016-09-04 17:29:57.302 EEST >LOG:  MultiXact member wraparound protections are now enabled
> < 2016-09-04 17:29:57.303 EEST >LOG:  database system is ready to accept connections
> < 2016-09-04 17:29:57.303 EEST >LOG:  autovacuum launcher started
> < 2016-09-04 17:35:37.594 EEST >LOG:  received fast shutdown request
> < 2016-09-04 17:35:37.594 EEST >LOG:  aborting any active transactions
> < 2016-09-04 17:35:37.595 EEST >LOG:  autovacuum launcher shutting down
> < 2016-09-04 17:35:37.596 EEST >LOG:  shutting down
> < 2016-09-04 17:35:37.602 EEST >LOG:  database system is shut down
> < 2016-09-04 17:36:42.313 EEST >LOG:  database system was shut down at 2016-09-04 17:35:37 EEST
> < 2016-09-04 17:36:42.313 EEST >LOG:  entering standby mode
> < 2016-09-04 17:36:42.315 EEST >LOG:  consistent recovery state reached at 0/3015860
> < 2016-09-04 17:36:42.315 EEST >LOG:  invalid record length at 0/3015860
> < 2016-09-04 17:36:42.315 EEST >LOG:  database system is ready to accept read only connections
> < 2016-09-04 17:36:43.713 EEST >LOG:  received promote request
> < 2016-09-04 17:36:43.713 EEST >FATAL:  terminating walreceiver process due to administrator command
> < 2016-09-04 17:36:43.713 EEST >LOG:  redo is not required
> < 2016-09-04 17:36:43.715 EEST >LOG:  selected new timeline ID: 2
> < 2016-09-04 17:36:43.815 EEST >LOG:  archive recovery complete
> < 2016-09-04 17:36:43.817 EEST >LOG:  MultiXact member wraparound protections are now enabled
> < 2016-09-04 17:36:43.818 EEST >LOG:  database system is ready to accept connections
> < 2016-09-04 17:36:43.818 EEST >LOG:  autovacuum launcher started
> < 2016-09-04 17:38:57.455 EEST >LOG:  terminating walsender process due to replication timeout
> < 2016-09-04 17:40:55.578 EEST >LOG:  received fast shutdown request
> < 2016-09-04 17:40:55.578 EEST >LOG:  aborting any active transactions
> < 2016-09-04 17:40:55.578 EEST >LOG:  autovacuum launcher shutting down
> < 2016-09-04 17:40:55.579 EEST >LOG:  shutting down
> < 2016-09-04 17:40:55.581 EEST >LOG:  database system is shut down
> < 2016-09-04 17:40:56.696 EEST >LOG:  database system was shut down at 2016-09-04 17:40:55 EEST
> < 2016-09-04 17:40:56.696 EEST >LOG:  entering standby mode
> < 2016-09-04 17:40:56.698 EEST >LOG:  consistent recovery state reached at 0/30159E0
> < 2016-09-04 17:40:56.698 EEST >LOG:  invalid record length at 0/30159E0
> < 2016-09-04 17:40:56.699 EEST >LOG:  database system is ready to accept read only connections
> < 2016-09-04 17:40:56.701 EEST >FATAL:  pg_hba.conf rejects replication connection for host "10.0.0.36", user "postgres", SSL off
> < 2016-09-04 17:40:56.701 EEST >FATAL:  could not connect to the primary server: FATAL:  pg_hba.conf rejects replication connection for host "10.0.0.36", user "postgres", SSL off
> 	
> < 2016-09-04 17:40:57.905 EEST >LOG:  received fast shutdown request
> < 2016-09-04 17:40:57.905 EEST >LOG:  aborting any active transactions
> < 2016-09-04 17:40:57.906 EEST >LOG:  shutting down
> < 2016-09-04 17:40:57.915 EEST >LOG:  database system is shut down

**Node2:** (Slave)

> < 2016-09-04 17:29:34.261 EEST >LOG:  database system was shut down at 2016-09-04 17:28:46 EEST
> < 2016-09-04 17:29:34.273 EEST >LOG:  MultiXact member wraparound protections are now enabled
> < 2016-09-04 17:29:34.275 EEST >LOG:  database system is ready to accept connections
> < 2016-09-04 17:29:34.275 EEST >LOG:  autovacuum launcher started
> < 2016-09-04 17:29:48.603 EEST >LOG:  received fast shutdown request
> < 2016-09-04 17:29:48.603 EEST >LOG:  aborting any active transactions
> < 2016-09-04 17:29:48.603 EEST >LOG:  autovacuum launcher shutting down
> < 2016-09-04 17:29:48.604 EEST >LOG:  shutting down
> < 2016-09-04 17:29:48.607 EEST >LOG:  database system is shut down
> < 2016-09-04 17:29:57.298 EEST >LOG:  database system was shut down at 2016-09-04 17:29:48 EEST
> < 2016-09-04 17:29:57.302 EEST >LOG:  MultiXact member wraparound protections are now enabled
> < 2016-09-04 17:29:57.303 EEST >LOG:  database system is ready to accept connections
> < 2016-09-04 17:29:57.303 EEST >LOG:  autovacuum launcher started
> < 2016-09-04 17:33:10.729 EEST >LOG:  database system was interrupted; last known up at 2016-09-04 17:30:54 EEST
> < 2016-09-04 17:33:10.740 EEST >LOG:  entering standby mode
> < 2016-09-04 17:33:10.742 EEST >LOG:  redo starts at 0/2000028
> < 2016-09-04 17:33:10.742 EEST >LOG:  consistent recovery state reached at 0/2000130
> < 2016-09-04 17:33:10.742 EEST >LOG:  database system is ready to accept read only connections
> < 2016-09-04 17:33:10.779 EEST >FATAL:  pg_hba.conf rejects replication connection for host "10.0.0.36", user "postgres", SSL off
> < 2016-09-04 17:33:10.779 EEST >FATAL:  could not connect to the primary server: FATAL:  pg_hba.conf rejects replication connection for host "10.0.0.36", user "postgres", SSL off
> 	
> < 2016-09-04 17:33:25.797 EEST >FATAL:  pg_hba.conf rejects replication connection for host "10.0.0.36", user "postgres", SSL off
> < 2016-09-04 17:33:25.798 EEST >FATAL:  could not connect to the primary server: FATAL:  pg_hba.conf rejects replication connection for host "10.0.0.36", user "postgres", SSL off
> 	
> < 2016-09-04 17:33:30.800 EEST >FATAL:  pg_hba.conf rejects replication connection for host "10.0.0.36", user "postgres", SSL off
> < 2016-09-04 17:33:30.801 EEST >FATAL:  could not connect to the primary server: FATAL:  pg_hba.conf rejects replication connection for host "10.0.0.36", user "postgres", SSL off
> 	
> < 2016-09-04 17:33:31.757 EEST >LOG:  received fast shutdown request
> < 2016-09-04 17:33:31.757 EEST >LOG:  aborting any active transactions
> < 2016-09-04 17:33:31.758 EEST >LOG:  shutting down
> < 2016-09-04 17:33:31.760 EEST >LOG:  database system is shut down
> < 2016-09-04 17:33:50.264 EEST >LOG:  database system was shut down in recovery at 2016-09-04 17:33:31 EEST
> < 2016-09-04 17:33:50.264 EEST >LOG:  entering standby mode
> < 2016-09-04 17:33:50.267 EEST >LOG:  redo starts at 0/2000028
> < 2016-09-04 17:33:50.267 EEST >LOG:  consistent recovery state reached at 0/3000000
> < 2016-09-04 17:33:50.268 EEST >LOG:  database system is ready to accept read only connections
> < 2016-09-04 17:33:50.271 EEST >LOG:  started streaming WAL from primary at 0/3000000 on timeline 1
> < 2016-09-04 17:35:37.832 EEST >LOG:  replication terminated by primary server
> < 2016-09-04 17:35:37.832 EEST >DETAIL:  End of WAL reached on timeline 1 at 0/3015860.
> < 2016-09-04 17:35:37.832 EEST >FATAL:  could not send end-of-streaming message to primary: no COPY in progress
> 	
> < 2016-09-04 17:35:37.832 EEST >LOG:  invalid record length at 0/3015860
> < 2016-09-04 17:35:46.082 EEST >LOG:  received fast shutdown request
> < 2016-09-04 17:35:46.082 EEST >LOG:  aborting any active transactions
> < 2016-09-04 17:35:46.083 EEST >LOG:  shutting down
> < 2016-09-04 17:35:46.097 EEST >LOG:  database system is shut down
> < 2016-09-04 17:36:42.551 EEST >LOG:  database system was shut down in recovery at 2016-09-04 17:35:46 EEST
> < 2016-09-04 17:36:42.551 EEST >LOG:  entering standby mode
> < 2016-09-04 17:36:42.560 EEST >LOG:  consistent recovery state reached at 0/3015860
> < 2016-09-04 17:36:42.560 EEST >LOG:  invalid record length at 0/3015860
> < 2016-09-04 17:36:42.561 EEST >LOG:  database system is ready to accept read only connections
> < 2016-09-04 17:36:45.191 EEST >LOG:  fetching timeline history file for timeline 2 from primary server
> < 2016-09-04 17:36:45.204 EEST >LOG:  started streaming WAL from primary at 0/3000000 on timeline 1
> < 2016-09-04 17:36:45.205 EEST >LOG:  replication terminated by primary server
> < 2016-09-04 17:36:45.205 EEST >DETAIL:  End of WAL reached on timeline 1 at 0/3015860.
> < 2016-09-04 17:36:45.206 EEST >LOG:  new target timeline is 2
> < 2016-09-04 17:36:45.206 EEST >LOG:  restarted WAL streaming at 0/3000000 on timeline 2
> < 2016-09-04 17:36:45.301 EEST >LOG:  redo starts at 0/3015860
> < 2016-09-04 17:38:13.774 EEST >LOG:  received promote request
> < 2016-09-04 17:38:13.774 EEST >FATAL:  terminating walreceiver process due to administrator command
> < 2016-09-04 17:38:13.775 EEST >LOG:  invalid record length at 0/3015970
> < 2016-09-04 17:38:13.775 EEST >LOG:  redo done at 0/3015938
> < 2016-09-04 17:38:13.777 EEST >LOG:  selected new timeline ID: 3
> < 2016-09-04 17:38:13.873 EEST >LOG:  archive recovery complete
> < 2016-09-04 17:38:13.874 EEST >LOG:  MultiXact member wraparound protections are now enabled
> < 2016-09-04 17:38:13.875 EEST >LOG:  database system is ready to accept connections
> < 2016-09-04 17:38:13.875 EEST >LOG:  autovacuum launcher started
> < 2016-09-04 17:39:05.133 EEST >LOG:  received fast shutdown request
> < 2016-09-04 17:39:05.133 EEST >LOG:  aborting any active transactions
> < 2016-09-04 17:39:05.133 EEST >LOG:  autovacuum launcher shutting down
> < 2016-09-04 17:39:05.134 EEST >LOG:  shutting down
> < 2016-09-04 17:39:05.136 EEST >LOG:  database system is shut down
> < 2016-09-04 17:39:06.245 EEST >LOG:  database system was shut down at 2016-09-04 17:39:05 EEST
> < 2016-09-04 17:39:06.245 EEST >LOG:  entering standby mode
> < 2016-09-04 17:39:06.255 EEST >LOG:  consistent recovery state reached at 0/3015B28
> < 2016-09-04 17:39:06.255 EEST >LOG:  invalid record length at 0/3015B28
> < 2016-09-04 17:39:06.255 EEST >LOG:  database system is ready to accept read only connections
> < 2016-09-04 17:39:06.257 EEST >FATAL:  pg_hba.conf rejects replication connection for host "10.0.0.36", user "postgres", SSL off
> < 2016-09-04 17:39:06.258 EEST >FATAL:  could not connect to the primary server: FATAL:  pg_hba.conf rejects replication connection for host "10.0.0.36", user "postgres", SSL off
> 	
> < 2016-09-04 17:39:21.274 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:26.281 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:31.279 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:36.287 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:41.290 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:46.297 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:51.300 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:39:56.306 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:01.312 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:06.316 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:11.321 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:16.324 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:21.330 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:26.336 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:31.342 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:36.347 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:41.353 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:46.357 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:51.363 EEST >FATAL:  highest timeline 2 of the primary is behind recovery timeline 3
> < 2016-09-04 17:40:56.367 EEST >FATAL:  could not connect to the primary server: could not connect to server: Connection refused
> 		Is the server running on host "10.0.0.36" and accepting
> 		TCP/IP connections on port 5432?
> 	
> < 2016-09-04 17:40:58.141 EEST >LOG:  received fast shutdown request
> < 2016-09-04 17:40:58.141 EEST >LOG:  aborting any active transactions
> < 2016-09-04 17:41:03.146 EEST >LOG:  shutting down
> < 2016-09-04 17:41:03.155 EEST >LOG:  database system is shut down

**Comment by ioguix** [comment]
Hello,

It's hard to read your log and understand the situation without the exact time for each operation and without the history of actions and commands.

But anyway: 

1) you MUST have fencing enabled. Especially on a two node cluster.
2) how do you disable the lan on old master ?
3) what happen on the old master side when you disable its lan connection ?
4) PAF does not support failback if a failure occurs. It only supports swapping master/slave role.

**Comment by ioguix** [comment]
Hi,

Any news here? Answers to my questions?
