### ISSUE TITLE
ocf:heartbeat:pgsqlms resource 

### ISSUE THREAD

**Issue by alimumcu1077** [dalibo/PAF#44]
Hello I wanna to learn when we use pgsqlms resource , replication is sync or async between database nodes ?

I used to  this config :
 
# pgsqld
pcs -f cluster1.xml resource create pgsqld ocf:heartbeat:pgsqlms \
    bindir=/usr/pgsql-9.3/bin pgdata=/var/lib/pgsql/9.3/data     \
    op start timeout=60s                                         \
    op stop timeout=60s                                          \
    op promote timeout=30s                                       \
    op demote timeout=120s                                       \
    op monitor interval=15s timeout=10s role="Master"            \
    op monitor interval=16s timeout=10s role="Slave"             \
    op notify timeout=60s                                        \

# pgsql-ha
pcs -f cluster1.xml resource master pgsql-ha pgsqld \
    master-max=1 master-node-max=1                  \
    clone-max=3 clone-node-max=1 notify=true

**Comment by ioguix** [comment]
Hello,

This is yours to decide. PAF does not deal with this, it just require the nodes to be in streaming replication. Should it be synchronous replication or asynchronous replication, it just doesn't matter.

Setting up streaming replication sync/async is a PostgreSQL related setup. In your postgresql.conf file, have a look at parameters `synchronous_commit` and `synchronous_standby_names`.

A strong recommendation: make sure to read PostgreSQL documentation about replication, its mechanism, how to setup it, manage it, what to be careful with, etc. This is outside the scope of PAF, we tried to draw a clear line between the DB setup and its high availability.
