### ISSUE TITLE
Precision about resource ordering

### ISSUE THREAD

**Issue by dud225** [dalibo/PAF#48]
Hello

The [howto](http://dalibo.github.io/PAF/Quick_Start-Debian-8.html) states that :
` WARNING: in step 4, the start/stop and promote/demote order for these resources must be asymetrical: we must keep the master IP on the master during its demote process.`
I don't understand quite well this statement in particular regarding the demote action. At the beginning the howto suggests to reject self-replication : 
```host replication postgres VIP/32 reject```
so far as I understand, the slave will be unable to connect to the master whether the master IP is here or not.

Could you give me some explanation about that ordering requirement ?

thanks
dud

PS : many may thanks for this awesome work ;)

**Comment by blogh** [comment]
Hi,

I am not from the devteam but I'll try to help.

The correct procedure for a switchover is to:
- stop the master:  during this process the postmaster will not stop until all wal files are sent to the connected standbies.
- wait for the standby to replay the wals
- promote the standy => new master
- start the old standby with a correct recovery.conf file => new standby

The VIP has to stay on the standby during the demote process (= stopping the resource) to ensure that all wal files are sent to the standbies

I think it was not possible before 9.3.
Please correct me if i am wrong.

Benoit

**Comment by ioguix** [comment]
Hi,

This is right @blogh. We need to keep the IP address on the demoting master so connections to standbies are not cut before everytging has been sent.

The fix has been pushed in 9.3 and backpatched to 9.1.

**Comment by dud225** [comment]
Hello.

Thanks for your detailed answer, that's pretty clear and it makes sense.

I'm just surprised about the sequence you wrote in the switchover procedure : "new master" then "new standby". I was expecting Pacemaker would do the opposite order, that is finish the whole stop process on the old master (demote PG then stop IP) before starting the new master (promote PG then start IP).

Also could you tell me which fix are you talking about ?

dud

**Comment by ioguix** [comment]
The transition pacemaker does is just the following one:
* demote old master (internally implemented in PAF as a stop/start)
* stop the IP address 
* promote new master
* start the IP address on the new master

So you are right @dud225.

I'll give you the fix reference later, I'm on my phone right now in an airport, not convenient :)

**Comment by ioguix** [comment]
Here is the link: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=985bd7d49726c9f178558491d31a570d47340459

More detailed info during a mail discussion on pcmk user list: https://www.mail-archive.com/users@clusterlabs.org/msg03549.html

**Comment by dud225** [comment]
Many thanks @ioguix for your answers, it is pretty clear to my mind now.
