### ISSUE TITLE
Debian packaging of 2.1

### ISSUE THREAD

**Issue by ioguix** [dalibo/PAF#53]
todo:

- [x] build Debian packages we provide on gh
- [x] ping @ge-fa for integration in stretch if released before 5th of january 2017 (see #13)

**Comment by ioguix** [comment]
Hi @ge-fa,

2.1_beta1 has been published. Packages are available (I tested them by upgrading PAF in my VMs). Any feedback is appreciated.

We plan to release 2.1 rc1 in next days, after some more tests, then 2.1 before Christmas hopefully.

Cheers,

**Comment by ge-fa** [comment]
@ioguix Great! Thanks for the notification! Unfortunately, right now I'm still quite busy with other projects and packaging. I'll ping the Debian HA people about the release, and keep you updated. Stay tuned!

**Comment by ioguix** [comment]
A quick update: I did a bunch of tests on a 3 node cluster and no regression so far. 

Here are the tests:

- recovery of a stopped standby
- recovery of a killed standby
- recovery of a stopped master
- recovery of a killed master
- moving the master role around
- banning the master role from a node
- banning the whole resource from a node
- restart the resource on a standby node (pcs resource restart)
- restart the resource on the master node (pcs resource restart)
- failover when migration-threshold is exhausted
- failover on node failure

I might publish a rc1 next week if there's no feedback.

**Comment by dud225** [comment]
Hi
Just to be sure : to upgrade PAF, there is nothing more to do after installing the new package, Pacemaler doesn't need to be restarted right ?
Regards.

**Comment by ioguix** [comment]
Hi @dud225,

> Just to be sure : to upgrade PAF, there is nothing more to do after installing the new package,
>Pacemaler doesn't need to be restarted right ?

Right. But I would recommend to put your cluster in maintenance mode before updating PAF.

I just wrote some doc about how to update PAF under CentOS 7. See: http://dalibo.github.io/PAF/CentOS-7-admin-cookbook.html#paf-update

**Comment by ioguix** [comment]
@ge-fa: v2.1.0 released :)
