### ISSUE TITLE
Modify quickstart doc

### ISSUE THREAD

**Issue by frost242** [dalibo/PAF#61]
Some modifications discussed together : 
  * [x] modify vip name pgsql-ha to pgsql-vip
  * [x] <del>move to recovery_template to /etc</del>
  * [x] <del>move pg_hba.conf to /etc</del>
  * [ ] add a warning about pg_hba.conf and recovery_template in PGDATA
  * [x] update quickstart to use PostgreSQL 9.6

**Comment by ioguix** [comment]
Update: we decided in #75 to not move recovery_template and pg_hba outside of PGDATA but just add a warning to the quick start.

**Comment by frost242** [comment]
Will do, but I don't know when.

**Comment by ioguix** [comment]
done in 80cfcc9d82f1f69aa0911b608dfaf719bc7b0f7c
