### ISSUE TITLE
Improve maxlag documentation / messages

### ISSUE THREAD

**Issue by blogh** [dalibo/PAF#73]
Hi, 

I think it would be nice to change this message to something more precise. Seeing a -1000 score in crm_mon can be very stressfull :). Maybe "Update score of "%s" from %s to %s because of a change in the replication lag." ?

```
_check_locations
            if ( $node_score ne $row->[1] ) {
                ocf_log( 'info', 'Update score of "%s" from %s to %s',
                    $row->[0], $node_score, $row->[1] );
                _set_master_score( $row->[1], $row->[0] );
            }
```

I also would like to modify the description of maxlag from:

> maxlag: maximum lag allowed on a standby before we set a negative master score on it. (default: 0, which disables this feature)

to 

> maxlag: maximum lag allowed on a standby before we set a negative master score on it. The calculation is based on the difference between the current xlog location on the master and the write location on the standby. (default: 0, which disables this feature)

because it could be based on flush or replay.

I'll do a PR if @ioguix and @frost242 are ok with the modifications.

Benoit

**Comment by ioguix** [comment]
Hi @blogh,

> Maybe "Update score of "%s" from %s to %s because of a change in the replication lag." ?

I would use:

~~~
Update score of "%s" from %s to %s because replication lag (%s) is higher than given maxlag (%s).
~~~

I'm ok with your suggestions.

**Comment by blogh** [comment]
I tried to make a more generic message because this portion of code is true for any change in score. If I read the SQL correctly the score is based on the row number of the standby based on write_location + application_name.

We can also add your message in case the score is -1000.

**Comment by ioguix** [comment]
Oh, ok.

Well, then you can test if the score is inferior to -1 to output this message as the negative master score for max-lagging slave decrease with a step of 10 (-1000, -990, -980, ...).

Note that -1 is already reserved for startup/backup streaming connexions.

**Comment by blogh** [comment]
will do thx.

**Comment by frost242** [comment]
Thanks Benoit

**Comment by blogh** [comment]
Hi, 

I started working on this yesterday (https://github.com/blogh/PAF/tree/maxlag not tested yet) and I am wondering if we should ditch write_location all together and keep only maxlag ? Since it's more invasive that it looked like to begin with I figured I should ask for your opinions first.

Benoit.

**Comment by ioguix** [comment]
Your patch looks good to me. As far as it works, I fine with pushing your patch.

Why would you like to ditch the write_location? I agree it's not really interesting, but it adds some more bits to the log message. I doesn't hurt at least :)

**Comment by blogh** [comment]
I was thinking that the write_location doesn't say much on its own and that the lag would be enough (and more meaningful). But then felt it was a lot of changes for a PR supposed to just change an information message.

I will leave it as is.

Thx for the feedback.

**Comment by ioguix** [comment]
I guess we can close this issue now?

**Comment by blogh** [comment]
I think so.
