### ISSUE TITLE
promotion fails because of missing lsn_location from attrd

### ISSUE THREAD

**Issue by gtyun** [dalibo/PAF#80]
Hi all,
I'm trying to set up 3 nodes in a cluster using PAF 2.1.0. I followed the Quick Start CentOS 6. But my nodes are not VM. So fence_virsh is not good and I do not know appropriate other fence-agent. So fencing is disabled.
`pcs -f cluster1.xml property set stonith-enabled="false"`
I believe this is not the reason for following trouble.

After psc cluster cib-push, any nodes cannot promote. 

pcs status
> Last updated: Tue Mar  7 21:08:30 2017		Last change: Mon Mar  6 18:19:04 2017 by root via crm_attribute on node03
Stack: cman
Current DC: node02 (version 1.1.14-8.el6_8.2-70404b0) - partition with quorum
3 nodes and 4 resources configured
Online: [ node02 node03 node04 ]
Full list of resources:
 Master/Slave Set: pgsql-ha [pgsqld]
     Slaves: [ node02 node03 node04 ]
 pgsql-master-ip	(ocf::heartbeat :IPaddr2):	Started node03
PCSD Status:
  node02: Online
  node03: Online
  node04: Online

/var/log/messages
>Mar  7 21:09:57 node03 rsyslogd-2177: imuxsock lost 352 messages from pid 9009 due to rate-limiting
Mar  7 21:09:57 node03 lrmd[9009]:  warning: pgsqld_notify_0 process (PID 21104) timed out
Mar  7 21:09:57 node03 lrmd[9009]:  warning: pgsqld_notify_0:21104 - timed out after 60000ms
Mar  7 21:09:57 node03 lrmd[9009]:   notice: pgsqld_notify_0:21104:stderr [ Could not query value of lsn_location: attribute does not exist ]
Mar  7 21:09:57 node03 lrmd[9009]:   notice: pgsqld_notify_0:21104:stderr [ Could not query value of recover_master: attribute does not exist ]
Mar  7 21:09:57 node03 lrmd[9009]:   notice: pgsqld_notify_0:21104:stderr [ Could not query value of nodes: attribute does not exist ]
Mar  7 21:09:57 node03 lrmd[9009]:   notice: pgsqld_notify_0:21104:stderr [ Could not query value of cancel_switchover: attribute does not exist ]
Mar  7 21:09:57 node03 lrmd[9009]:   notice: pgsqld_notify_0:21104:stderr [ Could not query value of lsn_location: attribute does not exist ]
* repeats ‘Could not query value of lsn_location’ 
...
>Mar  7 21:09:57 node03 rsyslogd-2177: imuxsock begins to drop messages from pid 9009 due to rate-limiting
Mar  7 21:09:57 node03 crmd[9012]:   notice: Operation pgsqld_notify_0: ok (node=node03, call=899, rc=0, cib-update=0, confirmed=true)
Mar  7 21:09:57 node03 pgsqlms(pgsqld)[22280]: INFO: pgsql_notify: promoting instance on node "node03"
Mar  7 21:09:57 node03 attrd[9010]:   notice: Sending flush op to all hosts for: lsn_location (<null>)
Mar  7 21:09:57 node03 attrd[9010]:   notice: Sent delete 11483: node=node03, attr=lsn_location, id=<n/a>, set=(null), section=status
Mar  7 21:09:57 node03 attrd[9010]:   notice: Sent delete 11485: node=node03, attr=lsn_location, id=<n/a>, set=(null), section=status
Mar  7 21:09:57 node03 pgsqlms(pgsqld)[22280]: INFO: pgsql_notify: current node LSN: 0/5000000
Mar  7 21:09:57 node03 attrd[9010]:   notice: Sending flush op to all hosts for: lsn_location (0/5000000)
Mar  7 21:09:57 node03 attrd[9010]:   notice: Sent update 11488: lsn_location=0/5000000
Mar  7 21:09:57 node03 attrd[9010]:   notice: Sent update 11490: lsn_location=0/5000000

pcs resource debug-promote pgsqld
>Error performing operation: Operation not permitted
Operation promote for pgsqld:0 (ocf:heartbeat :pgsqlms) returned 1
 >  stdout: /tmp:5432 - accepting connections
 >  stderr: pgsqlms(pgsqld:0)[32437]: 2017/03/07_21:18:35  DEBUG: _runas: launching as "postgres" command "/home/gtyun/work/postgres/bin/pg_isready -h /tmp -p 5432"
 >  stderr: pgsqlms(pgsqld:0)[32437]: 2017/03/07_21:18:35  DEBUG: pgsql_monitor: instance "pgsqld:0" is listening
 >  stderr: pgsqlms(pgsqld:0)[32437]: 2017/03/07_21:18:35  DEBUG: _query: psql return code: 0
 >  stderr: pgsqlms(pgsqld:0)[32437]: 2017/03/07_21:18:35  DEBUG: _query: @res: [
 >  stderr:           [
 >  stderr:             't'
 >  stderr:           ]
 >  stderr:         ]
 >  stderr: 
 >  stderr: pgsqlms(pgsqld:0)[32437]: 2017/03/07_21:18:35  DEBUG: _confirm_role: instance pgsqld:0 is a secondary
 >  stderr: pgsqlms(pgsqld:0)[32437]: 2017/03/07_21:18:35  DEBUG: pgsql_promote: "pgsqld:0" currently running as a standby
 >  stderr: Could not query value of cancel_switchover: attribute does not exist
 >  stderr: Could not query value of recover_master: attribute does not exist
 >  stderr: pgsqlms(pgsqld:0)[32437]: 2017/03/07_21:18:35  DEBUG: pgsql_promote: checking if current node is the best candidate for promotion
 >  stderr: Could not query value of nodes: attribute does not exist
 >  stderr: Could not query value of lsn_location: attribute does not exist
 >  stderr: 2017/03/07_21:18:35  CRIT: pgsql_promote: can not get current node LSN location

'pgsql_notify_pre_promote' deletes old value and update(or create) new values. So during promotion, lsn_location must be found, but it's not.
Also I tried to use 'attrd_updater' manually.
`#attrd_updater --private --lifetime reboot --name lsn_location --update 0/5000000`
`#attrd_updater --private --lifetime reboot --name lsn_location --query`
`Could not query value of lsn_location: attribute does not exist`

This result is not acceptable for me. 
If you need any other information, please let me know.

Thank you.

**Comment by ioguix** [comment]
Hello @gtyun,

PAF 2.x is not compatible with CentOS 6. See the warning in the release notes: https://github.com/dalibo/PAF/releases/tag/v2.1.0

> WARNING: This version is only compatible with at least Pacemaker 1.1.13 using a corosync 2.x stack.

What are your Pacemaker and Corosync versions?

You should probably consider version 1.1beta1 or upgrade to CentOS 7.

Considering your stonith problem, I suppose you have IPMI or DRAC or iLo card in your physical servers? If you do, a fencing agent exists for them. Eg. on a supermicro server IPMI card:

~~~
$ fence_ipmilan --action status --username ADMIN --password ADMIN --ip 192.168.42.3
OK
~~~

**Comment by gtyun** [comment]
Hello @ioguix ,

My Pacemaker version is 1.1.14 but Corosync version is 1.4.7. 
That's the problem. I'm going to consider PAF 1.1beta1 first.
After that I will check if my server has fencing device or not.

Thank you for your comment.

**Comment by gtyun** [comment]
I chagned PAF from 2.1.0 to 1.1beta1
>yum list | grep resource-agents-paf
>resource-agents-paf.noarch                  1.1~beta1-1                 @/resource-agents-paf-1.1.beta1-1.noarch

But the result of `pcs status` and `pcs resource debug-promote` is same above.

**Comment by ioguix** [comment]
Hi,

The promote action in PAF is done in two steps:
* pre-notify promote to everyone so they can set their lsn_location
* promote the designated resource clone as master

During this second step, PAF compare the local lsn_location with the other ones.

`pcs resource debug-promote` will not work as it force a local action without notifying other nodes, breaking the steps above.

Did you build a brand new cluster after installing 1.1b1 so we are free of failcounts, location constraints and so on in the cluster?

**Comment by gtyun** [comment]
I thought that my node processed 'pgsql_notify_pre_promote' and failed to promote. 
I tried with following commands.
`pcs cluster destroy --all`
`pcs cluster setup --name mycluster node02 node03 node04 --force`
`pcs cluster start --all`
`pcs cluster cib-push cluster1.xml`
I cannot find any sign or log of promotion. Every my nodes are slaves.

**Comment by ioguix** [comment]
Hi,

See: http://dalibo.github.io/PAF/configuration.html#postgresql-configuration

> Last but not least, during the very first startup of your cluster, the designated master will be the only instance stopped gently as a master. Take great care of this when you setup your cluster for the first time

As your instances have already been started as slave by your previous cluster setup, I suppose all your nodes where stopped as slave.

If you just want to trigger the promotion by hands, you can simply run the following command on the master node:

~~~
crm_master -l forever -r pgsqld -v 1
~~~

If you want to experience how PAF really handle this when you build a fresh startup (including the PostgreSQL instances), you just need to start/promote/stop the master instance by hands, then start your cluster. Eg.:

~~~
pcs cluster stop --all
su - postgres
/usr/pgsql-9.4/bin/pg_ctl -D /var/lib/pgsql/9.4/data start
/usr/pgsql-9.4/bin/pg_ctl -D /var/lib/pgsql/9.4/data promote
/usr/pgsql-9.4/bin/pg_ctl -D /var/lib/pgsql/9.4/data stop
exit
pcs cluster start --all
~~~

Note that after the first cluster startup, master scores are kept indefinitely by Pacemaker, so the promotion should occur on next start/reboot.

**Comment by ioguix** [comment]
Hi @gtyun,

How is it going now? Can we close this issue or do you have further questions related to it?

For your information, we plan to release 1.1 soon as it is considered stable now.

**Comment by gtyun** [comment]
Hi, @ioguix 

Sorry for late response.
What I want is experience how PAF handle postgresql.
But.. I could not build a fresh startup yet. 
After pg_ctl start/promote/stop and pcs cluster start, no nodes promotes.
My pgsql is 9.6 and it's compatible with PAF 1.1beta(Right? I checked release note).
So it doesn't matter I guess.

`crm_master -l forever -r pgsqld -v 1`
This command works properly promote node. But when the cluster restarts, there is still no promotion.

I'm planning to clean every cluster include postgresql and build new one. Not much expect.

**Comment by ioguix** [comment]
Mh, this is quite strange.

Yes, v1.1 is compatible with 9.6.

When your cluster does not promote any standby to master, could you provide us with your cluster setup, constraints and scores as shown by the following commands?

~~~
pcs config
pcs constraint
crm_simulate -sL
~~~

**Comment by gtyun** [comment]
The promotion score looks strange..

pcs config
>Cluster Name: mycluster
Corosync Nodes:
 node02 node03 node04
Pacemaker Nodes:
 node02 node03 node04

>Resources:
 Master: pgsql-ha
  Meta Attrs: master-max=1 master-node-max=1 clone-max=3 clone-node-max=1 notify=true 
  Resource: pgsqld (class=ocf provider=heartbeat type=pgsqlms)
   Attributes: bindir=/home/postgres/work/postgresql/bin system_user=postgres pgdata=/home/postgres/work/postgresql/data
   Operations: start interval=0s timeout=60s (pgsqld-start-interval-0s)
               stop interval=0s timeout=60s (pgsqld-stop-interval-0s)
               reload interval=0s timeout=20s (pgsqld-reload-interval-0s)
               promote interval=0s timeout=30s (pgsqld-promote-interval-0s)
               demote interval=0s timeout=120s (pgsqld-demote-interval-0s)
               monitor interval=15s role=Master timeout=10s (pgsqld-monitor-interval-15s)
               monitor interval=16s role=Slave timeout=10s (pgsqld-monitor-interval-16s)
               notify interval=0s timeout=60s (pgsqld-notify-interval-0s)
               meta-data interval=0s timeout=5s (pgsqld-meta-data-interval-0s)
               validate-all interval=0s timeout=5s (pgsqld-validate-all-interval-0s)

>Stonith Devices:
Fencing Levels:

>Location Constraints:
  Resource: pgsql-ha
    Enabled on: node02 (score:1) (id:location-pgsql-ha-node02-1)
Ordering Constraints:
Colocation Constraints:

>Resources Defaults:
 migration-threshold: 5
 resource-stickiness: 10
Operations Defaults:
 No defaults set
Cluster Properties:
 cluster-infrastructure: cman
 dc-version: 1.1.14-8.el6_8.2-70404b0
 have-watchdog: false
 stonith-enabled: false


pcs constraint
>Location Constraints:
  Resource: pgsql-ha
    Enabled on: node02 (score:1)
Ordering Constraints:
Colocation Constraints:

crm_simulate -sL

>Current cluster status:
Online: [ node02 node03 node04 ]

>Master/Slave Set: pgsql-ha [pgsqld]
     Slaves: [ node02 node03 node04 ]

>Allocation scores:
clone_color: pgsql-ha allocation score on node02: 1
clone_color: pgsql-ha allocation score on node03: 0
clone_color: pgsql-ha allocation score on node04: 0
clone_color: pgsqld:0 allocation score on node02: 11
clone_color: pgsqld:0 allocation score on node03: 0
clone_color: pgsqld:0 allocation score on node04: 0
clone_color: pgsqld:1 allocation score on node02: 1
clone_color: pgsqld:1 allocation score on node03: 10
clone_color: pgsqld:1 allocation score on node04: 0
clone_color: pgsqld:2 allocation score on node02: 1
clone_color: pgsqld:2 allocation score on node03: 0
clone_color: pgsqld:2 allocation score on node04: 10
native_color: pgsqld:0 allocation score on node02: 11
native_color: pgsqld:0 allocation score on node03: 0
native_color: pgsqld:0 allocation score on node04: 0
native_color: pgsqld:1 allocation score on node02: -INFINITY
native_color: pgsqld:1 allocation score on node03: 10
native_color: pgsqld:1 allocation score on node04: 0
native_color: pgsqld:2 allocation score on node02: -INFINITY
native_color: pgsqld:2 allocation score on node03: -INFINITY
native_color: pgsqld:2 allocation score on node04: 10
pgsqld:0 promotion score on node02: -1
pgsqld:1 promotion score on node03: -1
pgsqld:2 promotion score on node04: -1

**Comment by ioguix** [comment]
Hi,

I'm quite surprised by these scores:

~~~
pgsqld:0 promotion score on node02: -1
pgsqld:1 promotion score on node03: -1
pgsqld:2 promotion score on node04: -1
~~~

`-1` is set __by the master__ on pg_basebackup connexions or standby that are catching up...This does not make a lot of sens as that means a master has been found and it sets all the score in the cluster to `-1` itself.

If you can, could you try:
* put the cluster in maintenance mode
* promote one node with the master-pgsql-ip set on the node
* make sure all other node replicates correctly
* reset all the failcounts, master scores, location constraints
* cleanup and clear the pgsqld and pgsql-ha resources (no errors should raise)
* stop all the postgresql instances
* disable the pgsql-ha resource
* exit the maintenance mode
* wait for the cluster to be stable
* enable the pgsql-ha resource

Thank you.

**Comment by gtyun** [comment]
Hi,

I followed your suggestion

`pcs property set maintenance-mode=true`
And manually checks replication correctly..
`pcs resource cleanup pgsqld`
`pcs resource cleanup pgsql-ha`
`pcs resource cleanup pgsql-master-ip`
for each node : `pg_ctl stop -D pgdata`
`pcs resource disable pgsql-ha`
`pcs property set maintenance-mode=false`
`pcs resource enable pgsql-ha`

And it promotes node02 to master properly. 

But when I tried reset cluster ( pcs cluster destroy / setup / start / push cib), still there is no promotion occurred. I'm going to look over promotion scores.

**Comment by ioguix** [comment]
Hi,

I wonder if you have the same issue than @lucius-the on #86. See my answer there: https://github.com/dalibo/PAF/issues/86#issuecomment-286880669

**Comment by gtyun** [comment]
Hi @ioguix ,
My cluster works finally.
I clean up everything and correct some mis-configurations. I removed node03 from my cluster but the value of clone-max is still 3. I realized that from [#86 comment](https://github.com/dalibo/PAF/issues/86#issuecomment-286731940)

Following is my speculation.
`pcs cluster kill master' without stonith agent makes cluster to unavailable. 
After cluster kill, the new master tries to fence old master but can't. So new master cannot promote and get -INFINITY promotion score. The old master's promotion score is -INFINITY too. It looks like that accidently killed nodes get this score.
So every nodes are unavailable and cannot promote. Moreover, pgsql-master-ip is killed too. Each master and slave lost their replication connections and got different xlog_location. After that, re-created cluster do not work because of corrupted replication. 

It was very helpful of you to reply for me. Thank you very much.

**Comment by ioguix** [comment]
> After cluster kill, the new master tries to fence old master but can't. So new master cannot promote and get -INFINITY promotion score

Did you setup sbd/watchdog? I wonder if sbd would keep feeding the watchdog after a `pcs cluster kill`. If it does not, the failover might occurs as far as Pacemaker has `watchdog-enabled=true`. See the watchdog related doc: http://dalibo.github.io/PAF/CentOS-7-admin-cookbook.html#setting-up-a-watchdog

> It was very helpful of you to reply for me. Thank you very much

You are very welcome

**Comment by gtyun** [comment]
node02 was master and I killed node02. Then the /var/log/messages of node04 was like this.
>Mar 22 17:51:24 node04 fence_pcmk[429]: Call to fence node02 (reset) failed with rc=237
Mar 22 17:51:28 node04 fence_pcmk[472]: Requesting Pacemaker fence node02 (reset)
Mar 22 17:51:28 node04 stonith-ng[32483]:   notice: Client stonith_admin.cman.473.61352ef7 wants to fence (reboot) 'node02' with device '(any)'
Mar 22 17:51:28 node04 stonith-ng[32483]:   notice: Initiating remote operation reboot for node02: 91142682-2e16-4711-a968-b203ef9b2544 (0)
Mar 22 17:51:28 node04 stonith-ng[32483]:   notice: Couldn't find anyone to fence (reboot) node02 with any device
Mar 22 17:51:28 node04 stonith-ng[32483]:    error: Operation reboot of node02 by <no-one> for stonith_admin.cman.473@node04.91142682: No such device
Mar 22 17:51:28 node04 crmd[32487]:   notice: Peer node02 was not terminated (reboot) by <anyone> for node04: No such device (ref=91142682-2e16-4711-a968-b203ef9b2544) by client stonith_admin.cman.473

This messages is repeated. So I guessed like above speculation.

And my cluster do not have any watchdog. This is part of `pcs config`
> Cluster Properties:
 cluster-infrastructure: cman
 dc-version: 1.1.14-8.el6_8.2-70404b0
 have-watchdog: false
 stonith-enabled: false

Server needs stonith device or watchdog device to test failover. But my server do not have it. So softdog or VM server(with fence_virsh) could be a alternative. But I'm considering test with VM.
Thank you.

**Comment by ioguix** [comment]
Hi,

you need to install and setup sbd before Pacmaker could be able to detect the watchdog.

Most servers today have a watchdog device, sometime build in with the IPMI/iLo/DRAC card.

VM are also a useful way to test HA.

**Comment by gtyun** [comment]
Hi, 
The beginning was another matter. So the title was related to lsn_location. 
I think that vm is off topic and original problem is solved. 
I will try vm next time and if there is a problem, I will leave a comment again.
Thank you for your help in the meantime.
