### ISSUE TITLE
PAF on Centos7

### ISSUE THREAD

**Issue by lucius-the** [dalibo/PAF#86]
I'm having issues with PAF (lost several nights trying to get pgsql HA).
Tried to use another resource agent, the one that came with Centos7 but that one doesn't support replication slots. Went back to PAF.

The issue I have is that the master can't get promoted, because of some error in the script. It says:
Mar 14 18:23:28 dbhost1 pgsqlms(pgsqld)[10185]: INFO: pgsql_notify: promoting instance on node "dbhost1"
Mar 14 18:23:28 dbhost1 pgsqlms(pgsqld)[10185]: INFO: pgsql_notify: current node LSN: 0/17000000
Mar 14 18:23:28 dbhost1 lrmd[9844]:  notice: pgsqld_notify_0:10185:stderr [ Use of uninitialized value in hash element at /usr/lib/ocf/resource.d/heartbeat/pgsqlms line 1777. ]
Mar 14 18:23:28 dbhost1 crmd[9847]:  notice: Result of notify operation for pgsqld on dbhost1: 0 (ok)

I have a setup of 3 nodes, one last node is just used to give a vote. This is my pcs config:

Cluster Name: cluster_pgsql
Corosync Nodes:
 dbhost1 dbhost2 clusternode3
Pacemaker Nodes:
 clusternode3 dbhost1 dbhost2

Resources:
 Master: pgsql-ha
  Meta Attrs: master-node-max=1 clone-max=2 notify=true master-max=1 clone-node-max=2
  Resource: pgsqld (class=ocf provider=heartbeat type=pgsqlms)
   Attributes: bindir=/usr/pgsql-9.6/bin pgdata=/pgdata/pgsql/9.6/data
   Operations: start interval=0s timeout=60s (pgsqld-start-interval-0s)
               stop interval=0s timeout=60s (pgsqld-stop-interval-0s)
               promote interval=0s timeout=30s (pgsqld-promote-interval-0s)
               demote interval=0s timeout=120s (pgsqld-demote-interval-0s)
               monitor interval=15s role=Master timeout=10s (pgsqld-monitor-interval-15s)
               monitor interval=16s role=Slave timeout=10s (pgsqld-monitor-interval-16s)
               notify interval=0s timeout=60s (pgsqld-notify-interval-0s)
 Group: pgsql_ips
  Resource: pgsql-dbmaster-ip (class=ocf provider=heartbeat type=IPaddr2)
   Attributes: ip=10.15.20.20 cidr_netmask=24
   Operations: start interval=0s timeout=20s (pgsql-dbmaster-ip-start-interval-0s)
               stop interval=0s timeout=20s (pgsql-dbmaster-ip-stop-interval-0s)
               monitor interval=10s timeout=20s (pgsql-dbmaster-ip-monitor-interval-10s)
  Resource: pgsql-replmaster-ip (class=ocf provider=heartbeat type=IPaddr2)
   Attributes: ip=10.15.60.20 cidr_netmask=24
   Operations: start interval=0s timeout=20s (pgsql-replmaster-ip-start-interval-0s)
               stop interval=0s timeout=20s (pgsql-replmaster-ip-stop-interval-0s)
               monitor interval=10s timeout=20s (pgsql-replmaster-ip-monitor-interval-10s)
  Resource: pgsql-dbmaster-lan-ip (class=ocf provider=heartbeat type=IPaddr2)
   Attributes: ip=10.10.40.140 cidr_netmask=24
   Operations: start interval=0s timeout=20s (pgsql-dbmaster-lan-ip-start-interval-0s)
               stop interval=0s timeout=20s (pgsql-dbmaster-lan-ip-stop-interval-0s)
               monitor interval=10s timeout=20s (pgsql-dbmaster-lan-ip-monitor-interval-10s)

Stonith Devices:
Fencing Levels:

Location Constraints:
  Resource: pgsql-dbmaster-ip
    Enabled on: dbhost1 (score:200) (id:location-pgsql-dbmaster-ip-dbhost1-200)
    Enabled on: dbhost2 (score:100) (id:location-pgsql-dbmaster-ip-dbhost2-100)
    Disabled on: clusternode3 (score:-INFINITY) (id:location-pgsql-dbmaster-ip-clusternode3--INFINITY)
    Constraint: location-pgsql-dbmaster-ip (resource-discovery=never)
      Rule: score=-INFINITY  (id:location-pgsql-dbmaster-ip-rule)
        Expression: #uname eq clusternode3  (id:location-pgsql-dbmaster-ip-rule-expr)
  Resource: pgsql-ha
    Enabled on: dbhost1 (score:200) (id:location-pgsql-ha-dbhost1-200)
    Enabled on: dbhost2 (score:100) (id:location-pgsql-ha-dbhost2-100)
    Disabled on: clusternode3 (score:-INFINITY) (id:location-pgsql-ha-clusternode3--INFINITY)
    Constraint: location-pgsql-ha (resource-discovery=never)
      Rule: score=-INFINITY  (id:location-pgsql-ha-rule)
        Expression: #uname eq clusternode3  (id:location-pgsql-ha-rule-expr)
  Resource: pgsql_ips
    Enabled on: dbhost1 (score:200) (id:location-pgsql_ips-dbhost1-200)
    Enabled on: dbhost2 (score:100) (id:location-pgsql_ips-dbhost2-100)
    Disabled on: clusternode3 (score:-INFINITY) (id:location-pgsql_ips-clusternode3--INFINITY)
    Constraint: location-pgsql_ips (resource-discovery=never)
      Rule: score=-INFINITY  (id:location-pgsql_ips-rule)
        Expression: #uname eq clusternode3  (id:location-pgsql_ips-rule-expr)
Ordering Constraints:
  promote pgsql-ha then start pgsql_ips (kind:Mandatory) (id:order-pgsql-ha-pgsql_ips-mandatory)
  demote pgsql-ha then stop pgsql_ips (kind:Mandatory) (id:order-pgsql-ha-pgsql_ips-mandatory-1)
Colocation Constraints:
  pgsql-dbmaster-ip with pgsql-ha (score:INFINITY) (id:colocation-pgsql-dbmaster-ip-pgsql-ha-INFINITY)
Ticket Constraints:

Alerts:
 No alerts defined

Resources Defaults:
 migration-threshold: 5
 resource-stickiness: 10
Operations Defaults:
 No defaults set

Cluster Properties:
 cluster-infrastructure: corosync
 cluster-name: cluster_pgsql
 dc-version: 1.1.15-11.el7_3.4-e174ec8
 have-watchdog: false
 last-lrm-refresh: 1489512363
 maintenance-mode: false
 stonith-enabled: false
 symmetric-cluster: false
Node Attributes:
 clusternode3: master-pgsqld=-1000
 dbhost1: master-pgsqld=1

Quorum:
  Options:

Any help ?

**Comment by lucius-the** [comment]
My status is always like this:

Online: [ clusternode3 dbhost1 dbhost2 ]
Active resources:
 Master/Slave Set: pgsql-ha [pgsqld]
     Slaves: [ dbhost1 dbhost2 ]

dbhost1 never gets to run as a master.

**Comment by lucius-the** [comment]
Ok, noone there...
I've recreated the cluster again with a slightly more simple config. Now when I first start it all works. But after I try to stop dbnode1 (using pcs cluster stop) th cluster doesn't promote dbhost2, it stays as "Slave". Aftert trying to see why it doesn't promote (using pcs resource debug-promote pgsqld --full) I get this:

CRIT: pgsql_promote: can not get current node LSN location

Also the service on dbhost2 never starts now, either as Master or Slave.
In any case, other than first startup after cluster creation, I can't get this to work.

I am using streaming replication, with replication slots. Don't know if that matters. I've put the replication slot name in recovery.conf.pcmk and it works, after the first cluster start, before a node goes away and everything stops working.

**Comment by lucius-the** [comment]
Ok, recreated the cluster for the 20th time. It's all working well until I stop the cluster. When 2 of 3 nodes come up and I have quorum (one of those is just a voter, doesn't have postgresql on it and discovery is disabled), then one node (that was master before cluster stop) starts as a slave it doesn't promote to master because:

CRIT: pgsql_promote: can not get current node LSN location

This I think has to do with issue #9 might be same problem.
I've gone through #9 but I don't understand how to resolve it.

How do I start the resource after 1 node is gone and the other gets a machine restart ?

So far I have found no way at all to start through the cluster, even manually. But it should start automatically if cluster has quorum, I find it the whole point of HA cluster.

**Comment by ioguix** [comment]
Hello!

Sorry for the lack of answer, long day here as well...

First, debug-promote will never work properly with PAF as explained in [https://github.com/dalibo/PAF/issues/80#issuecomment-284878812](#80).

Second, I would be very curious to know how to trigger the perl warning you had in your first message. If there is a bug around the notify action, we would better want to now it and fix it. Any reproducible scenario would be really appreciated.

Third, unfortunately, PAF will not take care of slot replication for you. Basically, that means that you probably need to drop them and create them as soon as an instance starts as a standby, so the replication slots are ready should the standby be promoted.

Last but not least, Pacemaker will refuse to promote a slave if it can not define the status of the old master with perfect reliability. That usually means: it needs to be able to fence the remote node if the stop action fails.

If you are using virtual machine, I bet a fencing agent exists for your technology. If you are using bare-metal servers without fencing capability, think twice about your HA architecture. A good simple solution for trivial tests and scenario is at least to activate the watchdog. It will covers the most easy scenarios but will not save you should a network split occurs.

**Comment by ioguix** [comment]
PS: really late here, I'll follow up with your questions tomorrow.

**Comment by lucius-the** [comment]
Hello !
Thank you very much for reading through and reacting to issues I'm having.

About reproducing the issue, uhm... I've destroyed the cluster and recreated it quite a few times after that. If I do hit it again, will open another issue and provide steps leading to it. Although, the configuration posted above is the one that was used. I just tried to stop the cluster on one node to see if master will come alive on another node (using "pcs cluster stop" on the node I was going to kink out). Did that several times, and clicked on "Cleanup" button in Web UI from time to time (don't ask me why, I figured that sometimes it helps - but I've stopped doing that now).

If debug-promote doesn't work, uhm, how can I start the resource in this case ? I mean, maybe there is some command I'm just not aware of, I'm quite a noob with pcs and Linux-HA. I only found info for debug-promote.

I know replication slots need to be created on all postgresql instances in the cluster. I was not aware I have to recreate them. But it makes a lot of sense, actually. There shouldn't be a replication slot on the slave. That is, unless I want to hit disk space limits. Hm. Thanks for the tip :)

Regarding fencing. Reading your other posts, I've meanwhile come to understand this might be the reason. But it's really not the most obvious thing, the docs do state fencing is obligatory, however I didn't thing for a moment that the lack of it would cause such problems.

So yes STONITH is disabled on my cluster at the moment, idea was to add it after the initial basic testing was done. I had no idea missing fencing would mess things up like this. Does it mean if I implemented resource fencing from the beginning, I wouldn't be having this problem with resource promotion ? Is that correct ?

I'm using VM-s in vSphere for this, so I'll try with virsh and see if I can make it work. I did plan to implement STONITH, don't worry I'm aware of why it's a must, I just wasn't aware it was a necessity from the start. Still not sure it this is true or not. Will to add it see if things will change to the better.

Again, thank you very much for your help. I'll be off at another site tomorrow, so I can only try things out on Thursday. I will test & reply back as soon as possible.

**Comment by lucius-the** [comment]
Well... I added the fence devices (not using virsh, but using fence_vmware_soap) and switched the cluster back to STONITH enabled. My STONITH devices show up green in the web UI and they show as "started" in crm_mon.

But behaviour is still the same. After I stop clusters on both nodes (besides the "voter node"), and then start the cluster on one of the nodes (the one that was the last master) it still wont start as Master, but shows up as Slave an dstays like that. STONITH also didn't do a thing, I see the other node is still running. No errors about any failed operations in crm_mon though.

**Comment by lucius-the** [comment]
Ok, I found that things work better if I kick a node out with "killall -9 corosync" rather than "pcs cluster stop <node>". What is the difference in this I don't know, the latter also stops corosync.

But when I work with "killall -9 corosync" the cluster behaves differently and the resource does come back as Master rather than as Slave.

I still have the issue when the last node on which postgres can run is left makes a reboot (or stops the cluster). After restart I can not get this resource to run as Master until the other node comes back. This has nothing to to with quorum, btw, a third node is always running and quorum exists (the third node is just not running any posgtres instance).

So the issue remains... If I ever loose one of 2 nodes that can host the postgresql resource for good, my cluster will not be able to survive a reboot of the remaining node. The resource will never come up as Master. Very strange.

**Comment by blogh** [comment]
Hi @lucius-the,

Reading through your first post, I see that `clone-node-max=2`. Shouldn't it be set to 1 ?
I am still new to the project so I will let @ioguix answer you about your issues.

For my understanding : is your node fenced when you do the `killall  -9 corosync` ?

Thanks for your perseverance.

**Comment by lucius-the** [comment]
You're right, clone-node-max should be 1 and clone-max should be 2. This is how it's setup at the moment, but was incorrect at the beginning.

My node gets fenced shortly after `killall -9 corosync`. It gets rebooted, not a nice reboot, more like a reset button push if it were on the VM, but that is the right thing to do as I see it. Pacemaker and corosync services are disabled on all nodes, so the cluster doesn't come up after VM is reset, all is good.

Thanks for explaining the difference between `pcs cluster stop` and killing corosync :)

But the issue is still here. Let's say that 1 node burns up - mobo dies and the spirit leaves the electronics in the form of white smoke, never to come back (and we know electronics don't work without the white smoke). The other node will take over the master role - all good. But now it the that node (last survivor that can host the resource) every gets a machine reboot, there's no way to start the pgsql resource as master again. I've tested this, it always comes back as slave. Even though it was master before reboot. It won't promote to master until the other node (besides the "voter node" which on my test is always running) comes back.

An interesting observation: if the last node that can host the pgsql resource is not restarted, but I do a "reset" on the VM, then the resource does come back as Master. Only if I make a reboot (which probably does `pcs cluster stop` as part of the process) than the resource comes as Slave and remains so forever. I found no way to promote it to master at this point.

I figure this is somewhat corner case, but my idea is that cluster resource should be able to start as master, even if the other node might be gone for good. Adding fencing didn't change this behavior.

**Comment by lucius-the** [comment]
> I found no way to promote it to master at this point.

Update! I found a way to promote it to Master again. If I issue a cleanup for the resource with `pcs resource cleanup pgsql-ha`, it suddenly switches to Master. So a manual workaround is found. I wish it would do that automatically.

From what I read, the cleanup command only resets fail counts on the resource. But obviously it does something more than that, as `crm_mon` doesn't show any fails before I issue this command. Tested a couple of times, fully reproducible in my test setup.

**Comment by lucius-the** [comment]
My current cluster config

```
# pcs config
Cluster Name: cluster_pgsql
Corosync Nodes:
 dbhost1 dbhost2 clusternode3
Pacemaker Nodes:
 clusternode3 dbhost1 dbhost2

Resources:
 Master: pgsql-ha
  Meta Attrs: master-node-max=1 clone-max=2 notify=true master-max=1 clone-node-max=1
  Resource: pgsqld (class=ocf provider=heartbeat type=pgsqlms)
   Attributes: bindir=/usr/pgsql-9.6/bin pgdata=/pgdata/pgsql/9.6/data
   Operations: start interval=0s timeout=60s (pgsqld-start-interval-0s)
               stop interval=0s timeout=60s (pgsqld-stop-interval-0s)
               promote interval=0s timeout=30s (pgsqld-promote-interval-0s)
               demote interval=0s timeout=120s (pgsqld-demote-interval-0s)
               monitor interval=15s role=Master timeout=10s (pgsqld-monitor-interval-15s)
               monitor interval=16s role=Slave timeout=10s (pgsqld-monitor-interval-16s)
               notify interval=0s timeout=60s (pgsqld-notify-interval-0s)
 Resource: pgsql-master-ip (class=ocf provider=heartbeat type=IPaddr2)
  Attributes: ip=10.10.40.140 cidr_netmask=24
  Operations: start interval=0s timeout=20s (pgsql-master-ip-start-interval-0s)
              stop interval=0s timeout=20s (pgsql-master-ip-stop-interval-0s)
              monitor interval=10s (pgsql-master-ip-monitor-interval-10s)

Stonith Devices:
 Resource: fence_dbhost1 (class=stonith type=fence_vmware_soap)
  Attributes: port=564d80b9-b872-3c59-a00a-27838de774ac ipaddr=10.10.40.132 login=root passwd=XXX ssl_insecure=true
  Operations: monitor interval=60s (fence_dbhost1-monitor-interval-60s)
 Resource: fence_dbhost2 (class=stonith type=fence_vmware_soap)
  Attributes: port=564d30df-ba75-2f99-09d9-fd4e260ca065 ipaddr=10.10.40.129 login=root passwd=XXX ssl_insecure=true
  Operations: monitor interval=60s (fence_dbhost2-monitor-interval-60s)
Fencing Levels:
 Node: dbhost1
  Level 1 - fence_dbhost1
 Node: dbhost2
  Level 1 - fence_dbhost2

Location Constraints:
  Resource: pgsql-ha
    Disabled on: clusternode3 (score:-INFINITY) (id:location-pgsql-ha-clusternode3--INFINITY)
    Constraint: location-pgsql-ha (resource-discovery=never)
      Rule: score=-INFINITY  (id:location-pgsql-ha-rule)
        Expression: #uname eq clusternode3  (id:location-pgsql-ha-rule-expr)
  Resource: pgsql-master-ip
    Disabled on: clusternode3 (score:-INFINITY) (id:location-pgsql-master-ip-clusternode3--INFINITY)
    Constraint: location-pgsql-master-ip (resource-discovery=never)
      Rule: score=-INFINITY  (id:location-pgsql-master-ip-rule)
        Expression: #uname eq clusternode3  (id:location-pgsql-master-ip-rule-expr)
Ordering Constraints:
  promote pgsql-ha then start pgsql-master-ip (kind:Mandatory) (non-symmetrical) (id:order-pgsql-ha-pgsql-master-ip-mandatory)
  demote pgsql-ha then stop pgsql-master-ip (kind:Mandatory) (non-symmetrical) (id:order-pgsql-ha-pgsql-master-ip-mandatory-1)
Colocation Constraints:
  pgsql-master-ip with pgsql-ha (score:INFINITY) (rsc-role:Started) (with-rsc-role:Master) (id:colocation-pgsql-master-ip-pgsql-ha-INFINITY)
Ticket Constraints:

Alerts:
 No alerts defined

Resources Defaults:
 migration-threshold: 5
 resource-stickiness: 10
Operations Defaults:
 No defaults set

Cluster Properties:
 cluster-infrastructure: corosync
 cluster-name: cluster_pgsql
 dc-version: 1.1.15-11.el7_3.4-e174ec8
 have-watchdog: false
 last-lrm-refresh: 1489608546
Node Attributes:
 clusternode3: master-pgsqld=-1000
 dbhost1: master-pgsqld=1001
 dbhost2: master-pgsqld=1000

Quorum:
  Options:

```

**Comment by ioguix** [comment]
>Update! I found a way to promote it to Master again. If I issue a
>cleanup for the resource with `pcs resource cleanup pgsql-ha`, it
>suddenly switches to Master. So a manual workaround is found. I wish it
>would do that automatically.
>
>From what I read, the cleanup command only resets fail counts on the
>resource. But obviously it does something more than that, as `crm_mon`
>doesn't show any fails before I issue this command. Tested a couple of
>times, fully reproducible in my test setup.

I suspect the cleanup does nothing but waking up the cluster resource manager. Also known as: you might have a pending action that will be executed later, usually during next cluster recheck ( see cluster-recheck-interval).

You can confirm this by running this command that shows what the cluster would do if it wakes up:

```
crm_simulate -SL
```

And if you are facing this...I have no solution :-) Pending action appears when the cluster can not do everything in the same transition for some reasons. Maybe analyzing your logs would show something obvious...

**Comment by lucius-the** [comment]
Hi, thanks for replying and for the hint on `crm_simulate` command.

Nothing in the logs, checked them. But -> cluster_recheck_interval is 15 mins. That's... long. I don't think I waited that long. Why is that long, I wonder if there's any danger in setting it to 1 min.

Btw, since you know pretty much all, could you point me to some good/proper documentation on clustering. I know this seems like a very silly question for an open source package, but I'm having quite a bit of trouble finding good docs on clustering. What I find on clusterlabs is old like the bible and RedHat docs are quite scarce. Not much more than explaining (in as few words as possible) what a parametar means, but not many words on when to use it. I'm just grabbing bits of info here and there, trying to get it all together, very hard. PostgreSQL documentation, in comparison, is pure heaven. Or I just don't know where to look for clustering :)

**Comment by lucius-the** [comment]
Anyway, I'm drifting away from the topic now, feeling like I'm starting to abuse the issue tracking system.

The RA seems to work actually, once I set cluster_recheck_interval to 1 min. Perhaps we should close the issue.
```
Transition Summary:
 * Promote pgsqld:0     (Slave -> Master dbhost1)
 * Start   fence_dbhost1        (clusternode3)
 * Start   fence_dbhost2        (clusternode3)
 * Start   pgsql-master-ip      (dbhost1)
 * Start   pgsql-master-ip-vegalan      (dbhost1)
```

You were right on the nail again. You're a king mate, you helped me solve everything. Thank you so very much :) I want to buy you a beer :)

**Comment by ioguix** [comment]
> But -> cluster_recheck_interval is 15 mins

Agree...

> Why is that long, I wonder if there's any danger in setting it to 1 min.

I don't know. I suppose the only drawback is to waste some very little CPU cycles and pollutions in the cluster logs. And maybe some useless cluster communication on the network side.

Funnily, I sent an email about this exact issue on pacemake mailing list...a week ago. No answer so far. See: http://lists.clusterlabs.org/pipermail/users/2017-March/005251.html

> could you point me to some good/proper documentation on clustering

Not much :(
I agree documentation for Pacemaker would deserves some more love (and I agree PgSQL doc is pretty good!). We learned a lot while writing PAF, experiencing on it,  discussing on IRC/mailing lists with Pacemaker's devs, etc. Moreover, years ago, in Dalibo, we asked hastexo to come to our office for a two days training on Pacemaker. I did not experienced a lot between this training and PAF, but I kept some solid notes.

What I would recommend is to read:
* links from the [fencing page](http://dalibo.github.io/PAF/fencing.html)
* obviously, the [Pacemaker Explained](http://clusterlabs.org/doc/en-US/Pacemaker/1.1/html-single/Pacemaker_Explained/) page
* the [unixarena articles](http://www.unixarena.com/tag/pacemaker) sounds good (they are still on my TODO though)
* dig in the [alteeve](https://www.alteeve.com/w/Main_Page) wiki

It's quite late here, I probably forget some other good references. Do not hesitate to join the #clusterlabs chan on freenode as well. If some people are around, you might get some answers quickly.

And of course, if you can, try to find company that is doing training on Pacemaker, depending on your budget, your company policy, your localization, etc.

We wrote a draft of a training somewhere I might be able to finish, clean and publish at some point, but I need to discuss this with my colleague at Dalibo first.

> You were right on the nail again. You're a king mate, you helped me solve everything. Thank you so very much :) I want to buy you a beer :)

Heh, thank you, my pleasure :)

**Comment by lucius-the** [comment]
Thank you very much for links and all your help !
I'll read it but now I have to I finish redis cluster and a few things with hacluster and pgbouncer first. I want to have the whole setup running, then I can go into all the details (and probably come back here with something more) before I do with proper testing, documentation, etc.

**Comment by ioguix** [comment]
OK. Good luck with your setup.

++
