### ISSUE TITLE
Man page should not be pgsqlms.1 but something like ocf_heartbeat_pgsqlms.7

### ISSUE THREAD

**Issue by vuntz** [dalibo/PAF#88]
Right now, the man page is in section 1, but other resource agents man pages are in section 7, and have a slightly different naming scheme.

**Comment by ioguix** [comment]
Hi,

Thank you for the report. I've been quite busy lately sorry for the long delay :/ ...

I'll try to take care of this as soon as possible.

**Comment by ioguix** [comment]
I've been studying Module::Build to move and rename the man page, but with no success so far. It seems they both deal only with manpages of section 1 or section 3.

I might have to extend Module::Build to fix this :/

**Comment by ioguix** [comment]
I've been able to deal with Module::Build to build and install the man page in section 7.

...And I actually wrote the manpage that was quite empty :D

I still have to deal with packaging now and I'll be able to close this issue.

**Comment by ioguix** [comment]
I did some packaging test and everything seems fine and ready for the next release IRW the manpage.

Thank you for this report.
