### ISSUE TITLE
fencing ipmilan

### ISSUE THREAD

**Issue by alexseb76** [dalibo/PAF#89]
Hi all,
I have configured 2 nodes follwing the manual. The guests virtual machines are hosted on the Microsoft Hypervisor and I have choosed to configure the fence_ipmilan with DELL iDRAC Enterprise 8.

When I run the shutdown and or restart on the master node, the Virtual IP switch in second node, but when I run poweroff, the slave is not promoted as master.

Moreover, when the master is offline, the physical server no reboot.
Please, help me
Alessandro

**Comment by ioguix** [comment]
Hi,

I fail to understand what you are doing exactly. Could you reply to the following questions ?

* are you fencing the hypervisor hosting your VM using `fence_impilan`?
* what are the commands you are using to create all your fencing resources?
* when you "run shutdown or restart or poweroff", what are the exact commands you are typing?

**Comment by alexseb76** [comment]
Hi,
1)	I choose to fencing with ipmilan (DELL iDRAC 8) because with microsoft hyperv is not supported, with vmware the fencig works very well.
2)	The command is 
pcs resource create pgsql-master-ip ocf:heartbeat:IPaddr2  ip=192.168.10.140 cidr_netmask=32 op monitor interval=10s

pcs stonith create my-ipmilan-for-esimhost01 fence_ipmilan pcmk_host_list=esimhost01 ipaddr=192.168.1.101 action=reboot login=fencer passwd=exprivia lanplus=1 cipher=1 op monitor interval=60s
pcs constraint location my-ipmilan-for-esimhost01 avoids esimpaf01


pcs stonith create my-ipmilan-for-esimhost02 fence_ipmilan pcmk_host_list=esimhost02 ipaddr=192.168.1.102 action=reboot login=fencer passwd=exprivia lanplus=1 cipher=1 op monitor interval=60s

pcs constraint location my-ipmilan-for-esimhost02 avoids esimpaf02

3)	The commands are
a.	Reboot: 	shutdown –r now
b.	Shutdown: 	stutdown –h now
c.	Power-off:	turn off from the hypervisor console
Many thanks
Alessandro

**Comment by ioguix** [comment]
> I choose to fencing with ipmilan (DELL iDRAC 8) because with microsoft hyperv is not supported, with vmware the fencig works very well.

It's still not clear to me what the fencing resource is fencing. Is it only the VM itself using a virtual ipmi card or is it the hypervisor itself?

Did you test your fencing is working correctly?

I feel like when you run `shutdown {-r|-h} now` the node is leaving the cluster gently, so the cluster resource manager (CRM) knows all its resources are stopped in a clean way and can move everything to the second node.

When you reset your VM through the hypervisor console, the CRM would trigger a fencing action to make sure the node is off before moving everything to the second node. However, I suspect your fencing is failing, forbidding the CRM to move anything anywhere.

Do the following test: after the reset of the VM hosting the master, run `crm_simulate -SL`on the second node to show us what is the status of the cluster.

**Comment by alexseb76** [comment]
I want to restart the physical server if the Ppostgresql master fail in order to isolate this node from the cluster. I'm using the real card of the hypervisor.
Yes I tested the ipmi connection with this commands 
fence_ipmilan -P -a 192.168.1.101 -l fencer -p exprivia -o status -v
fence_ipmilan -P -a 192.168.1.101 -l fencer -p exprivia -o reboot -v

Do I have to reset the vm from the hypervisor?
Many thanks
Alessandro

**Comment by ioguix** [comment]
> Do I have to reset the vm from the hypervisor?

Reseting the hyperviser sounds overkill as you probably fence a bunch of other VM not related.

Could you show us the results of `crm_simulate -SL` and `pcs status` and `crm_mon -frAno1` when your cluster is "stuck"?

**Comment by alexseb76** [comment]
this is the results of the second node after the master reset 
Current cluster status:
Online: [ esimpaf01-cls esimpaf02-cls ]

 pgsql-master-ip        (ocf::heartbeat:IPaddr2):       Started esimpaf01-cls
 Master/Slave Set: pgsql-ha [pgsqld]
     Masters: [ esimpaf01-cls ]
     Slaves: [ esimpaf02-cls ]
 my-ipmilan-for-esimhost01      (stonith:fence_ipmilan):        Started esimpaf02-cls
 my-ipmilan-for-esimhost02      (stonith:fence_ipmilan):        Started esimpaf01-cls

Transition Summary:

Executing cluster transition:

Revised cluster status:
Online: [ esimpaf01-cls esimpaf02-cls ]

 pgsql-master-ip        (ocf::heartbeat:IPaddr2):       Started esimpaf01-cls
 Master/Slave Set: pgsql-ha [pgsqld]
     Masters: [ esimpaf01-cls ]
     Slaves: [ esimpaf02-cls ]
 my-ipmilan-for-esimhost01      (stonith:fence_ipmilan):        Started esimpaf02-cls
 my-ipmilan-for-esimhost02      (stonith:fence_ipmilan):        Started esimpaf01-cls

[root@esimpaf02 ~]# pcs status
Cluster name: pgcluster
Stack: corosync
Current DC: esimpaf02-cls (version 1.1.15-11.el7_3.4-e174ec8) - partition with quorum
Last updated: Wed Apr 19 16:38:19 2017          Last change: Wed Apr 19 14:42:26 2017 by root via crm_attribute on esimpaf01-cls

2 nodes and 5 resources configured

Node esimpaf01-cls: UNCLEAN (offline)
Online: [ esimpaf02-cls ]

Full list of resources:

 pgsql-master-ip        (ocf::heartbeat:IPaddr2):       Started esimpaf01-cls (UNCLEAN)
 Master/Slave Set: pgsql-ha [pgsqld]
     pgsqld     (ocf::heartbeat:pgsqlms):       Master esimpaf01-cls (UNCLEAN)
     Slaves: [ esimpaf02-cls ]
 my-ipmilan-for-esimhost01      (stonith:fence_ipmilan):        Started esimpaf02-cls
 my-ipmilan-for-esimhost02      (stonith:fence_ipmilan):        Started[ esimpaf02-cls esimpaf01-cls ]

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled
[root@esimpaf02 ~]# crm_mon -frAno1
Stack: corosync
Current DC: esimpaf02-cls (version 1.1.15-11.el7_3.4-e174ec8) - partition with quorum
Last updated: Wed Apr 19 16:38:23 2017          Last change: Wed Apr 19 14:42:26 2017 by root via crm_attribute on esimpaf01-cls

2 nodes and 5 resources configured

Node esimpaf01-cls: UNCLEAN (offline)
        pgsqld  (ocf::heartbeat:pgsqlms):       Master
        pgsql-master-ip (ocf::heartbeat:IPaddr2):       Started
        my-ipmilan-for-esimhost02       (stonith:fence_ipmilan):        Started
Node esimpaf02-cls: online
        pgsqld  (ocf::heartbeat:pgsqlms):       Slave
        my-ipmilan-for-esimhost01       (stonith:fence_ipmilan):        Started
        my-ipmilan-for-esimhost02       (stonith:fence_ipmilan):        Started

No inactive resources


Node Attributes:
* Node esimpaf02-cls:
    + master-pgsqld                     : 1000

Operations:
* Node esimpaf02-cls:
   pgsqld: migration-threshold=1000000
    + (20) start: rc=0 (ok)
   my-ipmilan-for-esimhost01: migration-threshold=1000000
    + (19) start: rc=0 (ok)
    + (21) monitor: interval=60000ms rc=0 (ok)
   my-ipmilan-for-esimhost02: migration-threshold=1000000
    + (26) start: rc=0 (ok)

**Comment by ioguix** [comment]
I'm not sure of the signification of `UNCLEAN (offline)`, but it might be that the node is offline, but not confirmed by a fencing yet. Which would confirm my theory.

Moreover, it seems to me the `crm_simulate -SL` is inconsistent with the two other commands as it shows `esimpaf01-cls` online where it is shown as offline on other commands.

When your cluster is stuck in this state, could you run the following command to confirm the cluster the node is really down to see if it move resources on the other side: `pcs stonith confirm esimpaf01-cls`

**Comment by alexseb76** [comment]
pcs stonith confirm esimpaf01-cls
WARNING: If node esimpaf01-cls is not powered off or it does have access to shared resources, data corruption and/or cluster failure may occur. Are you sure you want to continue? [y/N] y
Node: esimpaf01-cls confirmed fenced

**Comment by alexseb76** [comment]
When I reset the vm the status is unclean

pgsql-master-ip        (ocf::heartbeat:IPaddr2):       Started esimpaf01-cls (UNCLEAN)
 my-ipmilan-for-esimhost01      (stonith:fence_ipmilan):        Started esimpaf02-cls
 my-ipmilan-for-esimhost02      (stonith:fence_ipmilan):        Started[ esimpaf02-cls esimpaf01-cls ]
 Master/Slave Set: pgsql-ha [pgsqld]
     pgsqld     (ocf::heartbeat:pgsqlms):       Master esimpaf01-cls (UNCLEAN)
     Slaves: [ esimpaf02-cls ]

**Comment by ioguix** [comment]
So? Did the `pcs stonith confirm` command changed anything? Did the resources moved? The node status changed?
