### ISSUE TITLE
pgsqlms does not work with pacemaker_remote

### ISSUE THREAD

**Issue by q53** [dalibo/PAF#91]
resource-agents-paf-1.1.0-1.noarch on SL7 with postgres9.6 in a openvz container configured with pacemaker-remote-1.1.15-11.el7_3.4.
pgsqlms definition on crmsh:

```
ms MS_POSTGRESAUX postgresaux \
        meta master-max=1 master-node-max=1 clone-max=3 clone-node-max=1 notify=true 
primitive postgresaux pgsqlms \
        params bindir="/usr/pgsql-9.6/bin" pgdata="/var/lib/pgsql/9.6/data" \
        op start timeout=60s interval=0 \
        op stop timeout=60s interval=0 \
        op promote timeout=30s interval=0 \
        op demote timeout=120s interval=0 \
        op monitor interval=15s timeout=10s role=Master \
        op monitor interval=16s timeout=10s role=Slave \
        op notify timeout=60s interval=0
```

Resources running fine until you try to promote a slave.
After set an environment to manually execute pre notify:

```
# /usr/lib/ocf/resource.d/heartbeat/pgsqlms notify                                                                           [608/1921]
DEBUG: pgsql_notify: environment variables: {
  'active' => [],
  'demote' => [],
  'inactive' => [],
  'master' => [],
  'operation' => 'promote',
  'promote' => [
                 {
                   'rsc' => 'MS_POSTGESAUX',
                   'uname' => 'postgres-aux-2'
                 }
               ],
  'slave' => [],
  'start' => [],
  'stop' => [],
  'type' => 'pre'
}

INFO: pgsql_notify: promoting instance on node "postgres-aux-2"
DEBUG: _query: psql return code: 0
DEBUG: _query: @res: [
  [
    '1645/7D4D0520'
  ]
]

INFO: pgsql_notify: current node LSN: 1645/7D4D0520
sh: /usr/sbin/crm_attribute: No such file or directory
DEBUG: _set_attr: waiting to set "lsn_location=1645/7D4D0520" (currently "")...
DEBUG: _set_attr: waiting to set "lsn_location=1645/7D4D0520" (currently "")...
DEBUG: _set_attr: waiting to set "lsn_location=1645/7D4D0520" (currently "")...
DEBUG: _set_attr: waiting to set "lsn_location=1645/7D4D0520" (currently "")...
DEBUG: _set_attr: waiting to set "lsn_location=1645/7D4D0520" (currently "")...

```

Looks like pgsqlms calls crm_attribute which part of pacemaker and failing.
Any chances for support of pacemaker-remote in the future?

**Comment by ioguix** [comment]
Hi,

First, under SL7 I suppose you should use PAF 2.x, not 1.1. I know the 1.1 has been released after the 2.x, but 1.1 is only a maintenance release for old OS. See release notes about this.

Second, I never played with pacemaker_remote so far, bu according to the documentation, it should work perfectly. See: http://clusterlabs.org/doc/en-US/Pacemaker/1.1/html-single/Pacemaker_Remote/#_accessing_cluster_tools_from_guest_node

According to the same doc, you should install the pacemaker package on guests: See: http://clusterlabs.org/doc/en-US/Pacemaker/1.1/html-single/Pacemaker_Remote/#_configure_pacemaker_remote
