### ISSUE TITLE
problems in pg_hba.con

### ISSUE THREAD

**Issue by crisras27** [dalibo/PAF#94]
hi i want to create a three node cluster using centOS 7 with PAF pacemaker and postgresql with the quick start in the page of dalibo in git hub but when i want to start the service of the postgres says that have a problem whit the pg_hba.conf in these lines

host replication postgres 192.168.122.50/32 reject
host replication postgres $(hostname -s) reject

< 2017-05-20 19:16:52.539 CDT > LOG:  máscara IP «reject» no válida: Nombre o servicio desconocido
< 2017-05-20 19:16:52.539 CDT > CONTEXTO:  línea 91 del archivo de configuración «/var/lib/pgsql/9.6/data/pg_hba.conf»
< 2017-05-20 19:16:52.539 CDT > LOG:  método de autentificación «-s)» no válido
< 2017-05-20 19:16:52.539 CDT > CONTEXTO:  línea 92 del archivo de configuración «/var/lib/pgsql/9.6/data/pg_hba.conf»
< 2017-05-20 19:16:52.539 CDT > FATAL:  no se pudo cargar pg_hba.conf
< 2017-05-20 19:16:52.542 CDT > LOG:  el sistema de bases de datos está apagado

excuse for the spanish but says in a few words IP mas reject not valid : name or service unknown
line 91 of the file  «/var/lib/pgsql/9.6/data/pg_hba.conf»
autentication method -s) not valid in line 92

**Comment by ioguix** [comment]
Hi @crisras27,

It seems you did not execute the exact command to edit the `pg_hba.conf` as given in the quick start.

When executed as given in the quick start, `$(hostname -s)` is supposed to be replaced with the hostname of each nodes. You are not supposed to have this string in the file.
